linkedin/cruise-control

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java
This is a pretty strait forward patch. Will add LoadMonitor unit tests later.
> Fix num valid windows bug. Add back the rebalance listener for CruiseControlMetricReporterSampler.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
- cruise-control/src/test/resources/log4j.properties
Fixed an issue that rack did not set the broker state correctly.
Fixed RackAwareCapacityGoal flow to fallback to continue with replica movement if leader movement does not work.
> Added lower bound for ResourceDistributionGoal.

- README.md
- Rephrase, fix typos, and other minor updates.
> Go over the Wiki to clarify a few details.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
* Fixed the case that the goals except the first goal are ignored during self-healing.
* Make optimization slightly faster
> Fix self healing

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
This may happen when the oldest log segment is deleted from the broker when Cruise Control is being deployed.
> Handle the OffsetOutOfRangeException in KafkaSampleStore

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
> Fix minor typo in AnalyzerState.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java
Currently API queries are case sensitive. Make them case insensitive.
> Make API queries case insensitive.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/Goal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/RandomCluster.java
This patch fixes the issue https://github.com/linkedin/cruise-control/issues/75.
> Enforce exclusion of given topics in goal optimization.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
* Remove redundant parameter _with_available_valid_windows_ -- instead use a single parameter _with_available_valid_partitions_ (default is false).
* Raise User Request Exception if request contains invalid endpoint parameters. In the existing version of CC, if user request contains non-existing parameters, CC silently ignores them. As a result, the user might incorrectly assume that her parameter is acknowledged by CC.
* Implement appropriate JSON responses.
* Add `throttle_added_broker` parameter to be used while adding a new, throttled broker.
> Refactor Rest API:

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionTarget.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java
The execution of CC may generate different set of proposals for the same goals.
This patch stabilizes the goal execution by providing consistent optimization order.
> Stabilize the goal execution by providing consistent optimization order.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetStateRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/RetrievingMetrics.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManagerTest.java
* Add kafka-assigner mode to the servlet.
* Make state retrieval asychronous as well.
> Add kafka-assigner mode to the servlet.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricCompletenessChecker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
* Fix start-time misinterpretation in partition_load request
* Add clarification to Monitored Windows times in verbose state.
> Fix start-time misinterpretation in partition_load request.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
* Fix stats overwrite in case of multiple unknown hosts.
* Add leader count per broker/replica.
> Update broker and host stats in proposals

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This patch changes the way executor carries out the proposals. Instead of doing on replica at a time, it take the entire partition as a single execution unit.
> Fix the proposal execution.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
This patch fixes Issue https://github.com/linkedin/cruise-control/issues/131
> Order printed host stats by host-id.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/141.
> Fix failure to move excluded topic replica from decommissioned broker in kafka assigner mode.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/ReadOnlyKafkaSampleStore.java
This patch fixes the Issue https://github.com/linkedin/cruise-control/issues/113.
> Add missing default value for num.sample.loading.threads.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
For example, `partition_load?resource=CPU&entries=10` will return the top 10 entries.
> Add a parameter to enforce a limit on the number of entries in partition load response

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
* Add pause and resume sampling endpoints to Cruise Control Servlet (Issue https://github.com/linkedin/cruise-control/issues/153).
> Add pause and resume sampling endpoints to Cruise Control Servlet.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManager.java
* Fix response is committed error upon closing a session (Issue https://github.com/linkedin/cruise-control/issues/136).
> Fix response is committed error upon closing a session.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
> Fix a typo in partitionSampleExtrapolations

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/173.
> Pass through exception message to REST API response.

- config/cruisecontrol.properties
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/MetricSample.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MetricAnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/metricdefinition/KafkaMetricDef.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/BrokerMetricSample.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingFetcher.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaBrokerMetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SampleLoadingTask.java
This patch rebases on master and fixed a few issues before we can merge this dev branch back to master.
> Patch before merging back

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
Fixes NPE issues in 
1. https://github.com/linkedin/cruise-control/issues/219.
2. https://github.com/linkedin/cruise-control/issues/218.
> Fix metric anomly NPE.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
necessary code changes to send the exceptions as valid json.
> fix #222: send stacktraces as valid json

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/CruiseControlUtils.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinder.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinderConfig.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java
* Fix the broken date format in anomaly descriptions.
* Add the number of entries in the history to the anomaly description.
* Add metric anomaly upper and lower margin.
> Fix metric anomaly detection.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/249.
> Accept JSON as URL parameter for demote_broker.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationFuture.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgress.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
fix for https://github.com/linkedin/cruise-control/issues/224
return format will be
{name: {description: xxx,
time: xxx,
completionPercentage:xxx }
...
}
also fix the JSON response of GET state
> fix JSON version of inprogress response

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
fix for https://github.com/linkedin/cruise-control/issues/230
return same information as non-JSON response, with both verbose set or not.
> fix JSON response to GET proposals request

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
fix for https://github.com/linkedin/cruise-control/issues/268
fix JSON response to recognize verbose parameter in get state request
add goal readiness information in verbose JSON response
fix bug  in super_verbose scenario CC respond incorrectly if there is no training progress
> Fix JSON response for get state request(#268)

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationFuture.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgress.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/279.
> Change the JSON operation progress response Map to Array.

- build.gradle
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterSslTest.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCAbstractZookeeperTestHarness.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBroker.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBrokerBuilder.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedZookeeper.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaClientsIntegrationTestHarness.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaIntegrationTestHarness.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaTestUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
- gradle/wrapper/gradle-wrapper.properties
* Bump up Kafka and Kafka-clients dependency to 2.0.0
* Remove dependency on li-apache-kafka-clients
* Rebase code to work with Kafka 2.0.0.
> Bump up Kafka version to 2.0.0

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetStateRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/283.
> Enable state endpoint queries to specify substates to be queried.

- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCAbstractZookeeperTestHarness.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBroker.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBrokerBuilder.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedZookeeper.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaIntegrationTestHarness.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
Remove (1) reflection from `CCEmbeddedBroker`, and (2) the redundant workaround from `CCEmbeddedZookeeper`.
> Refactor Metrics Reporter test harness.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaClusterState.java
- gradle/wrapper/gradle-wrapper.properties
* Fixes the issue https://github.com/linkedin/cruise-control/issues/288.
* Bumps up the gradle version to `4.8`.
> Make kafka_cluster_state report offline replicas.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
THROTTLE_REMOVED_BROKER_PARAM is not a valid parameter for add_broker endpoint.
> remove invalid parameter for add_broker endpoint

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/ReadOnlyKafkaSampleStore.java
Add following three configs to KafkaCruiseControlConfig.
1. num.sample.loading.threads
2. partition.metric.sample.store.topic
3. broker.metric.sample.store.topic
> Add num.sample.loading.threads to KafkaCruiseControlConfig

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/330.
> Ensure that demote_broker operation is throttled only by concurrent leader movements config.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/329.
> Remove the irrelevant excluded_topics parameter from demote_broker endpoint.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/355.
> Catch the exception if a non-existing goal is specified in the parameter.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java
By default the application listens on loopback address `(127.0.0.1)` and the users can override this behaviour by passing a hostname or ip address to listen on as a last argument to the server.
> Allow bind address to be specified (#275)

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaClusterState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AnomalyNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/NoopNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
This patch adds anomaly substate under the state endpoint.
> Add anomaly detector state.

- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/async/OperationFutureTest.java
Fixes the failures in `testCancelInProgressFuture` due to lack of semaphore.
> Fix concurrency bug in cancel in progress test.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaUserTaskState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Add support for the issue https://github.com/linkedin/cruise-control/issues/380.
> Add parameter to filter user_tasks based on the given user_task_ids.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AddBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DecommissionBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Add support for the issue https://github.com/linkedin/cruise-control/issues/382.
> Add triggeredUserTaskId to Executor substate.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/387.
> Make completed user task retention time configurable.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/388.
> Add retention based on the number of completed user tasks.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/390.
> Make maximum number of active user tasks configurable.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgress.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgressTest.java
fix for issue [400](https://github.com/linkedin/cruise-control/issues/400).
> Fix the bug that rebalance request can only refer to one precomputing proposal task

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
Current returned time information is 12 hour format but does not have `am/pm` information, change to 24 hour format.
> Change the time format for time information in Servlet response.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/PreferredLeaderElectionGoalTest.java
patch for issue[403](https://github.com/linkedin/cruise-control/issues/403)
> Add parameter skip_under_replicated_partition and skip_reorder_replica to demote_broker endpoint.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BrokerStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/SingleBrokerStats.java
Added disk util in percentage to load endpoint. Also corrected presentation of CPU util to be "percent". Also made minor java doc fix.
> Added disk util percentage to load endpoint

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/411.
> Ensure that kafka_cluster_state endpoint shows brokers with no replicas.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AbstractParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AdminParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/BaseParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/BootstrapParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ClusterLoadParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/CruiseControlStateParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/KafkaClusterStateParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ProposalsParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TrainParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/UserTasksParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/422.
> Add admin endpoint with dynamic control over self healing.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
In Cruise Control 2.0 support for JBOD, we add the logic to populate logdir information to `kafka_cluster_state` endpoint. However, in a corner case where a broker is dead, getting its logdir from Kafka `AdminClient` will timeout, in current code the TimeOutException directly terminate the execution and the an abrupt response is returned to client. This patch is to enhance this behavior to proper encode the timeout and return to client with other broker/partition information.
> Add logic to handle getting broker log dir information timeout scenario.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
fix for [issue 437](https://github.com/linkedin/cruise-control/issues/437).
> Fix the bug in increasing sample store topic's replication factor.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AdminParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/431.
> Enable dynamic changes to the partition and leadership concurrency of an ongoing execution via admin endpoint.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SamplingTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/BaseParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PauseResumeParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
Addresses the request in issue https://github.com/linkedin/cruise-control/issues/424.
> Enable Cruise Control to identify the entity that paused/resumed load monitoring

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/447.
> Fix missing anomaly reporting when Goal Violation Detector fails due to OptimizationFailureException.

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/RawMetricType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/BrokerMetricSample.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/PartitionMetricSample.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/BrokerMetricSampleTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
Resolved the issue https://github.com/linkedin/cruise-control/issues/440.
> Make the broker metric sample creation backwards compatible.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/460.
> Fix unhandled concurrency issue when there is an exception in best proposal precomputation.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/461.
> Fix race condition between the controller and Cruise Control, which causes drop in effective partition movement concurrency.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/474.
> Ensure that goal violation detector does not attempt to self heal unfixable goals.

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinder.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorState.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValues.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/LinearRegressionModelParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/DefaultMetricSamplerPartitionAssignor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/BootstrapTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SamplingTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/483.
> Guard costly trace- and debug-level logging to avoid unnecessary resource use.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/485.
> Fix concurrency bug with default goals in proposal candidate computer.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/494.
> Ensure that offline brokers do not trigger goal violation detection or its self healing.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
Fixes the issue https://github.com/linkedin/cruise-control/issues/496.
> Preserve desired partition reassignment concurrency in Kafka 1.1.0+.

- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
Rollback the initial fix for https://github.com/linkedin/cruise-control/issues/496.
The fix for this issue requires a server-side (i.e. Kafka) fix.
Unfortunately, Partition reassignment concurrency in Kafka 1.1.0+ cannot be preserved due to controller code change. Hence, the executions in these versions that are using open source Kafka 1.1.0+ will perform executions in batches rather than continuously keeping the concurrency at a certain level.
So it is expected the user to observe saw-tooth shaped URP plots during executions.
> Rollback partition reassignment concurrency fix in Kafka 1.1.0+

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
fix for [506](https://github.com/linkedin/cruise-control/issues/506)
> Increase replication factor of Cruise Control topics in none rack-aware way if there are not enough racks in the cluster.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/518.
> Make OptimizationFailureException messages more clear.

- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
bug found while investigating a [build failure](https://circleci.com/gh/linkedin/cruise-control/1372)
> Fix occasional build failure due to inappropriate mocking behavior.

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/Anomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/473.
> Add self-healing state under anomaly detector state.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/533.
> Add missing logs describing the impact of admin operations.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/UserTasksParameters.java
Added some documentation for user_tasks endpoint.
> Add doc for new usertasks params

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/536.
> Add OPTIMIZATION_RESULT upon self-healing anomalies under anomaly_detection substate.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/543.
> Fix bad formatting in plaintext response of admin result.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetProposalsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalShuffleTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OfflineProposalGenerator.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/554.
> Ignore proposal cached when there is ongoing execution.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/550.
> Suppress goal violation detection while there is an ongoing execution.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ProposalsParameters.java
`ignore_proposal_cache` is in the docstring twice.
Accordingly, remove the last one.
> Remove redundant ignore_proposal_cache parameter

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionTarget.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/530.
> Refactoring to ensure that optimization failures are clear and consistent.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
fix for issue [541](https://github.com/linkedin/cruise-control/issues/541)
> Mark failed user task's state as CompletedWithError in UserTaskManager.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/565.
> Ensure that case insensitive user requests are handled properly.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/568.
> Add common abstraction for servlet requests.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/575.
> Improve default static model coefficients for CPU estimation.

- README.md
Addresses the issue https://github.com/linkedin/cruise-control/issues/607.
> Update Environment Requirements

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
fix for bug described in [599](https://github.com/linkedin/cruise-control/issues/599).
> Fix the bug that only one sample store topic's replication factor can increase in bootup sanity check.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
Fix for issue [611](https://github.com/linkedin/cruise-control/issues/611)
> Fix formatting issue in user_tasks endpoint's plaintext response.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/Goal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/614.
> Remove deprecated optimize method from Goal Interface

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
`broker.failure.detection.threshold.ms` should be `broker.failure.alert.threshold.ms`
> Fix incorrect broker.failure parameter name in code comment

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/purgatory/Purgatory.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/620.
> Ensure that the purgatory response for requests added to purgatory are discardable.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/Goal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/603.
> Ensure that no soft goal moves replicas away from healthy brokers during broker failures.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/EndPoint.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ReviewBoardParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/purgatory/Purgatory.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ReviewResult.java
Addresses the issues https://github.com/linkedin/cruise-control/issues/618 and https://github.com/linkedin/cruise-control/issues/619.
> Add review board endpoint and handle endpoint access attempts when two-step verification is disabled.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
Fix for [PR-597](https://github.com/linkedin/cruise-control/issues/597).
> Make Cruise Control return 500 response if it fails to retrieve broker logDir information

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/ActionAcceptance.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/ActionType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasTest.java
Extract changes in [PR-516](https://github.com/linkedin/cruise-control/pull/516) which are applicable to master branch.This helps to make the code base in two branches more consistent and reduce the works for future cherry-pick between branches.
> Refactor executor code.

- checkstyle/checkstyle.xml
- checkstyle/suppressions.xml
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/internals/BrokerAndSortedReplicas.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/OptimizationForGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackMessage.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/ModelGeneration.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingFetcher.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/DeterministicClusterTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForLeadershipTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForReplicaMoveTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifierTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/636.
> Add a checkStyle regarding the MemberName starting with underscore.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AbstractParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/CruiseControlParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/purgatory/RequestInfo.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ReviewResult.java
Fix for issue [647](https://github.com/linkedin/cruise-control/issues/647).
> Fix bugs in Cruise Control's processing logic for review and review_board request

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java
as brought up in [PR-516](https://github.com/linkedin/cruise-control/pull/516)
> Minor code cleanup.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/650.
> Ensure that logs are clear when there are no proposals to execute for the given goals.

- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
as brought up in [PR-516](https://github.com/linkedin/cruise-control/pull/516)
> Minor code cleanup in executor test code.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AddBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DecommissionBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetProposalsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ProposalsParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveBrokerParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Addresses the issues https://github.com/linkedin/cruise-control/issues/657 and https://github.com/linkedin/cruise-control/issues/660.
> Support picking specific destination brokers for broker removals, rebalance, and proposals

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
patch for [issue-671](https://github.com/linkedin/cruise-control/issues/671)
> Add intra.broker.goals config to specify supported intra-broker goals.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AnomalyNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AnomalyType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/NoopNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Patch for [issue-588](https://github.com/linkedin/cruise-control/issues/588)
> Add a new anomaly type for disk failures.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/674.
> Avoid repeating the common response in plaintext optimization result.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
Fix for [issue-676](https://github.com/linkedin/cruise-control/issues/676)
> Change ClusterModelStats to calculate replica statistics based on alive brokers.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingConstraint.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveBrokerParameters.java
Fix the errors reported when trying to push new jar to maven local.
> Clean up comment issues reported by Maven publish.

- README.md
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifierTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/681.
> Improve performance and accuracy of anomaly detector.

- build.gradle
- buildSrc/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Addresses the issue https://github.com/linkedin/cruise-control/issues/683.
> Upgrade Gradle version to 4.10.3.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
Fix for issue [690](https://github.com/linkedin/cruise-control/issues/690).
> Fix the bug in calculating replica statistics in cluster model.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Fix for issue [704](https://github.com/linkedin/cruise-control/issues/704).
> Fix the bug in executor that will fail all the self-healing operations.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/714.
> Remove the tight pause loop in metrics reporter sampler.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/UserTasksParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AbstractCruiseControlResponse.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
Address [issue 720](https://github.com/linkedin/cruise-control/issues/720) and [feature reqeust 531](https://github.com/linkedin/cruise-control/issues/531).
> Add support to fetch the full response of a completed task from user_tasks endpoint.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
> Fix Cruise Control initialization issue if reconnect.backoff.ms is not explicitly set in config.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AdminParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/719.
> Add support to dynamically remove brokers from recently demoted/removed brokers.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
> Fix Cruise Control initialization issue with reconnect.backoff.ms config.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Fix the missing log message in https://github.com/linkedin/cruise-control/issues/718.
> Refactor logs to (1) indicate user triggered stop execution and (2) fix missing detailed exception message while configuring sample store topics

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- Set SslConfigs if Security Protocol is either SSL or SASL_SSL
- Set SaslConfigs.SASL_JAAS_CONFIG as Password Config
> Fix Client Context for SASL_SSL

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterSslTest.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
> Expose linger.ms and batch.size config of KafkaProducer used in CruiseControlMetricsReporter.

- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/EndPoint.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/purgatory/RequestInfo.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Fixes issue #605,  issue #598,  issue #571.
> Sematic categorization of user task for retention

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/740.
> Fix NPE in TopicReplicaDistributionGoal during broker removal / fixing offline replicas.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java
> Prevent LeaderReplicaDistributionGoal generating leadership transfer operations during self-healing.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/Goal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionAbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/745.
> Clean up memory after goal optimizations to reduce memory pressure.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/KafkaClusterStateParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
Addresses issue #697 
Adds topic parameter in `GET /kafka_cluster_state` to filter verbose output based on topic parameter with matching regex
> Filter kafka cluster by topic

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AbstractCruiseControlResponse.java
Fix issue #751 and issue #752.
> Fix the user task state bookkeeping bug in UserTaskManager.

- build.gradle
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/common/config/ConfigDef.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBroker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/285 (except `ZooKeeperClient` -> `ZkClient` migration) and bumps up dependencies.
> Fix use of deprecated/unsafe APIs and bump up dependencies.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Addresses https://github.com/linkedin/cruise-control/issues/754 and https://github.com/linkedin/cruise-control/issues/747.
> Ensure that the anomaly detector can be shutdown cleanly and fix flaky anomaly detector tests.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
> Fix initialization issue with reconnect.backoff.ms config.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/764.
> Reset sensors for number of pending actions upon an execution stop request

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Addresses the issue https://github.com/linkedin/cruise-control/issues/778.
> Upgrade Gradle version to 5.4.1

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/692.
> Make self healing goals configurable

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/768.
> Fix concurrency bug causing reporting broker failures from future.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/792.
> Ensure that self.healing.goals can be configured with fully-qualified class names.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/internals/BrokerAndSortedReplicas.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
> Fix the bug that ReplicaDistributionGoal generates proposal to move replica from broker not hosting it.

- cruise-control-client/cruisecontrolclient/client/ExecutionContext.py
- cruise-control-client/cruisecontrolclient/client/cccli.py
- cruise-control-client/setup.py
Since it is expected that users of this client may modify `cccli.py` for their own convenience, this PR attempts to modularize the `cccli.py` interface to the core cruise-control python client.
> Modularize cli

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ProgressResult.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/814.
> Fix losing the progress information due to clearing futures in ProgressResult

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
Address the issue https://github.com/linkedin/cruise-control/issues/813.
> Fix NPE upon each request with a random non-existing UUID.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/NoopNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
Addresses the issues https://github.com/linkedin/cruise-control/issues/818 and https://github.com/linkedin/cruise-control/issues/819.
> Fix NPE upon retrieving the response of anomaly detector.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/800.
> Add sanity check for negative review ids.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetBrokerStatsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ClusterLoadParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java
> Make Cruise Control generate cluster load profile for specific time range.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
> Update resource statistics in ClusterModelStats to be consistent with resource distribution goals.

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AnomalyNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/723.
> Add anomaly metrics: (1) meanTimeBetweenAnomalies (2) meanTimeToStartFix, and (3) numSelfHealingStarted.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java
> Change the exception thrown when servlet parsing user request.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/Resource.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
> Increase resource EPSILON_PERCENT to avoid fake cluster model sanity check failure.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
> Make anomaly metrics readable.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/855.
> Add sensors on meanTimeToStartFixMs, numSelfHealingStarted, and ongoingAnomalyDurationMs.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
> Fix wrong operation progress for cluster model generation in response.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/866.
> Move the abstract logic from Load Monitor to the corresponding utils class.

- cruise-control-client/cruisecontrolclient/client/Endpoint.py
- cruise-control-client/setup.py
> Support all topic_configuration parameters

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
> Clarify all-topics at replication factor exception

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizerResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityInfo.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/PartitionLoadState.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OfflineProposalGenerator.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/PreferredLeaderElectionGoalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/RandomCluster.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
The remaining work towards addressing the issue: https://github.com/linkedin/cruise-control/issues/884.
> Make model/analyzer take heterogeneous CPU cores into account.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/PreferredLeaderElectionGoalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/RandomCluster.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/899.
> Fix populating replica placement info regardless of the populateReplicaPlacementInfo parameter.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ReplicationFactorChangeTest.java
> Specify topic to change replication factor in request body to topic_configuration endpoint.

- CONTRIBUTING.md
- config/cruisecontrol.properties
- cruise-control-client/cruisecontrolclient/client/Display.py
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizerResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/RawAndDerivedResource.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomGoalTest.java
- docs/wiki/Overview.md
Addresses the issue https://github.com/linkedin/cruise-control/issues/901.
> Add balancedness metric.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/AddBrokerRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/ClusterLoadRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/CruiseControlStateRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/DemoteRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/FixOfflineReplicasRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/PartitionLoadRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/ProposalsRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/RebalanceRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/RemoveBrokerRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/TopicConfigurationRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/AdminRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/BootstrapRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/KafkaClusterStateRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/PauseRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/ResumeRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/ReviewBoardRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/ReviewRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/StopProposalRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/TrainRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/UserTasksRequest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/912.
> Make servlet requests extensible.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtils.java
> Fix bug in processing metrics records for brokers not listed in metadata

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/Resource.java
> Increse absolute epsilon value of disk resource.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/935.
> Fix invalid cast of TopicConfigurationParameters to KafkaOptimizationParameters in OptimizationResult.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/937.
> Fix partitions with infinite CPU utilization in low-traffic clusters.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/945.
> Ensure that latest demoted and removed brokers are updated w/o NPE.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
> Fix the bug that Cruise Control prematurely thinks some replica movement tasks are done.

- cruise-control-client/setup.py
I forgot to make this part of #944
> Version bump to distinguish semver fix

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
> Change the default partition sample aggregation granularity to ENTITY.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
> Rename triggeredUserTaskId field in executor state to triggeredTaskId.

- config/cruisecontrol.properties
Addresses the issue https://github.com/linkedin/cruise-control/issues/967.
> Remove unintentional override of anomaly.detection.interval.ms config.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
> Make broker demoting operation honor config max.num.cluster.movements.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/AdminRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AdminParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ChangeExecutionConcurrencyParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/FixOfflineReplicasParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicReplicationFactorChangeParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/963.
> Support dynamically changing the metadata check frequency during executions.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/StopProposalRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/StopProposalParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
> Add support to uncleanly stop proposal execution.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/FixOfflineReplicasParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PauseResumeParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ReviewParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicReplicationFactorChangeParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- docs/wiki/User Guide/Configurations.md
- docs/wiki/User Guide/REST-APIs.md
> Add support to force user specifying reason for requests which trigger operation.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MetricAnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SampleLoadingTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/ProposalsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
> Support executing operations which require no valid window when load monitor is loading.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasHelper.java
Addresses the issue: https://github.com/linkedin/cruise-control/issues/998.
> Fix JavaDoc with bad style yielding publishJavaPublicationToMavenLocal failures.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/994.
> Show controller information in Kafka Cluster State.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
> Improve notification message from ExecutorNotifier.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/992.
> Eliminate superfluous broker failure notifications.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- docs/wiki/User Guide/REST-APIs.md
Addresses the issue https://github.com/linkedin/cruise-control/issues/1003.
> Change the default for "exclude_follower_demotion" during demote from false to true.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1001.
> Fix the bug causing the replica movement concurrency to go down to 1 during an execution.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1017.
> Fix NPE upon attempting to increase partition count of Kafka Sample Store topics

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1019.
> Remove dependency on DynamicConfig MODULE$

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1021.
> Allow customization of KafkaSampleStore

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1017.
> Fix NPE upon attempting to increase partition count of Kafka Sample S…tore topics (due to null manual replica reassignment).

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/StopProposalParameters.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1026.
> Ensure that PreferredReplicaLeaderElectionPath is never updated when the zNode exists.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/Goal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionAbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1024.
> Provide obvious/clear exception messages for optimization failures due to hard goal violations.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
> Make slow broker execution alerts to be sent out in batch.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
Respect the `sasl.login.callback.handler.class` config if specified
> add sasl.login.callback.handler.class to AdminClient configs if exists

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java
> Make PreferredLeaderElectionGoal to always pick the first replica in replica list as new leader.

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/GetStateRunnable.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
- docs/wiki/User Guide/Configurations.md
Addresses the issue https://github.com/linkedin/cruise-control/issues/1032 and code refactoring.
> Remove deprecated config metric.reporter.topic.pattern.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/GeneratingClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/WaitingForOngoingExecutionToStop.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AddedOrRemovedBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/DemoteBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/FixOfflineReplicasParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RebalanceParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveBrokerParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicReplicationFactorChangeParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/yaml/endpoints/rebalance.yaml
Addresses https://github.com/linkedin/cruise-control/issues/1034.
> Add support to modify ongoing executions

- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RequestParameterTest.java
- cruise-control/src/yaml/base.yaml
- cruise-control/src/yaml/endpoints/admin.yaml
- cruise-control/src/yaml/endpoints/bootstrap.yaml
- cruise-control/src/yaml/endpoints/fixOfflineReplicas.yaml
- cruise-control/src/yaml/endpoints/kafkaClusterState.yaml
- cruise-control/src/yaml/endpoints/partitionLoad.yaml
- cruise-control/src/yaml/endpoints/pauseSampling.yaml
- cruise-control/src/yaml/endpoints/rebalance.yaml
- cruise-control/src/yaml/endpoints/resumeSampling.yaml
- cruise-control/src/yaml/endpoints/review.yaml
- cruise-control/src/yaml/endpoints/reviewBoard.yaml
- cruise-control/src/yaml/endpoints/stopProposalExecution.yaml
- cruise-control/src/yaml/endpoints/train.yaml
- cruise-control/src/yaml/responses/adminResult.yaml
- cruise-control/src/yaml/responses/bootstrapResult.yaml
- cruise-control/src/yaml/responses/kafkaClusterState.yaml
- cruise-control/src/yaml/responses/pauseSamplingResult.yaml
- cruise-control/src/yaml/responses/resumeSamplingResult.yaml
- cruise-control/src/yaml/responses/reviewResult.yaml
- cruise-control/src/yaml/responses/stopProposalResult.yaml
- cruise-control/src/yaml/responses/trainResult.yaml
- docs/wiki/User Guide/REST-APIs.md
> Add open API yaml spec for multiple endpoints.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalReadinessRecord.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetails.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MeanTimeBetweenAnomaliesMs.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SelfHealingEnabledRatio.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/KafkaAnomalyType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/ModelCompletenessRequirements.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java
- cruise-control/src/yaml/base.yaml
- cruise-control/src/yaml/endpoints/state.yaml
- cruise-control/src/yaml/responses/analyzerState.yaml
- cruise-control/src/yaml/responses/anomalyDetectorState.yaml
- cruise-control/src/yaml/responses/cruiseControlState.yaml
- cruise-control/src/yaml/responses/executorState.yaml
- cruise-control/src/yaml/responses/loadMonitorState.yaml
Adds yamls and annotations for the State endpoint
> Schemafy state endpoint

- LICENSE
Addresses the issue https://github.com/linkedin/cruise-control/issues/1054.
Happy new year to Cruise Control community!
-- Wish you all healthy and balanced Kafka clusters :)
> Add 2020 to LICENSE.

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/Anomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokers.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/yaml/responses/anomalyDetectorState.yaml
Addresses the issue #1057 and #1061.
> Handle self-healing operations with no proposals to execute.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
> Skip broker with no log flush metrics in slow broker detection.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
> Fix the wrong metric id used in SlowBrokerDetector.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
> Fix bad config name that cause demotion to fail.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
> Add sensors to indicate whether self-healing is turned on/off for each self-healing option.

- cruise-control/access.log
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
> Fix balancedness criteria of ResourceDistributionGoal.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
Make the utils methods public so that if user want to implement customized goals in other packages, they can use the these utils methods.
> Make methods in GoalUtils public.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
> Fix the JSON response of state endpoint.

- build.gradle
> Bump up slf4j-api and junit.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
> Ensure that failures to fix an anomaly due to inability to optimize combined self-healing goals is logged in OPERATION_LOG.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
> Fix the bug that skip_urp_demotion and exclude_follower_demotion parameter does not work in broker demotion.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/holder/BrokerMetricSample.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
> Add a sensor to indicate whether the goal violation detector has unfixable goals.

- build.gradle
- gradle.properties
Extracts the Kafka version into gradle.properties for easier handling.
> Extracting kafka version

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokers.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
> Ensure that self healing goal violations do not report empty goal violations in ExecutorState.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/AnalyzerConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/AnomalyDetectorConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/ExecutorConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/UserTaskManagerConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java
- docs/wiki/User Guide/Configurations.md
Addresses the issue #1012 and adds documentation on capacity config.
> Add capacity config documentation and expose hardcoded defaults for optional configs.

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterSslTest.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerState.java
>  Make CruiseControlReporter check metrics topic's partition count during bootstrap

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
> Fix ConcurrentModificationException thrown by SlowBrokerFinder.

- build.gradle
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- gradle.properties
Addresses the issue #1120 and updates the access to the deprecated producer close API.
> Update stale dependencies and the access to the deprecated producer close API.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokers.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/GoalBasedOperationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/ProposalsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicReplicationFactorChangeParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
> Add an additional abstraction layer for goal-based operation runnables.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomalyFinder.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
> Skip replication factor self-healing if topic's minISR is larger than target replication factor.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/exception/OngoingExecutionException.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
> Add custom exception to disambiguate exceptions due to ongoing executions.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/ProposalsRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
> add_broker should drop brokers-to-be-added from recently-removed-brokers

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtAuthenticator.java
> Fix JavaDoc issues in JwtAuthenticator.

- docs/wiki/User Guide/REST-APIs.md
> Revamp the wiki section on using UUID and cookies.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
> Enable the use of RecentBrokers helper class outside the RunnableUtils.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifier.java
Addresses the issue #1136 
---
First time contributing, so apologies if the convention is to wait for the issue to be triaged before creating the PR 😸
> Report more descriptive message from the SlackSelfHealingNotifier (#1136)

- cruise-control-client/cruisecontrolclient/client/CCParameter/SetOfChoicesParameter.py
- cruise-control-client/setup.py
> [ccclient-1.0.5] Fix incorrect resource parameter choices

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokers.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomalyFinder.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinderTest.java
> Make slow broker finder more configurable and improve detection accuracy

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
> Make GoalViolationDetector and GoalOptimizer more extendible.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
> Fix NullPointerException thrown by SlowBrokerFinder.

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/ReadOnlyKafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtilsTest.java
> Use AdminClient for topic creation and config updates.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
> Fix the bug that stop_ongoing_execution parameter does not work.

- .circleci/config.yml
- checkstyle/checkstyle.xml
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/common/config/ConfigDef.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/common/utils/Utils.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinder.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionState.java
* Ensure that circleci workflow fails early due to malformed JavaDocs
* Ensure that the at-clause tags are followed by description.
Addresses the issues #1163 and #1164.
> Improve the JavaDoc style checks and circleci workflow.

- build.gradle
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- gradle.properties
Addresses the issue #1104 
* Added I0Itec zkclient dependency as it has been removed from Kafka
* `KafkaZkClient.getAllTopicsInCluster`'s return type changed from Seq to Set
* `AdminZkClient.addPartition`'s `existingAssignment`'s parameter type changed
> Upgrade Kafka dependency to 2.4

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java
Addresses the issue #1172.
The approach here is not to catch any thrown exception, but let it terminate the main thread and have its stack trace printed out.
> #1172: The main class hides any exceptions and prints a usage message

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomaly.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinderTest.java
Addresses the issue #1176  and #1178
> Further tune slow broker finder sensitivity

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomalyFinder.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomalyFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
> Make TopicReplicationFactorAnomalyFinder ignore topic with large minISR.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/strategy/AbstractReplicaMovementStrategy.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
Addresses the issue #1183, #1126 
- Change test case to re-produce the IllegalStateException in #1183.
- Copy commits made from https://github.com/liftoffio/cruise-control/pull/1 and bring into master branch
- Force chaining with BaseReplicaMovementStrategy when strategy changes dynamically
> Fix 1183 chained replica movement strategies

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/AnalyzerConfig.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
> Add missing sanity check for goals.

- README.md
- config/cruisecontrol.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinder.java
Addresses the issues #1204 and #1205.
> Update the interested metrics used by the metric anomaly analyzer and the anomaly notifier section in README.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorAdminUtils.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Addresses the issue #1218.
-- Also picks up the relevant refactoring from 1f6214203076b97ed788ccef7815a6184a3d9438.
> Fix flaky test ExecutorTest#testTimeoutAndForceExecutionStop()

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
> Allow customization of CruiseControlMetricsReporterSampler

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectionStatus.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MetricAnomalyDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicAnomalyDetector.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/SelfHealingWithOptimizedGoalTest.java
> Fix reported balancedness when there are offline brokers.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
This PR resolves https://github.com/linkedin/cruise-control/issues/1175.
> Ensure consistent rackID during topic_configuration operations to avoid NPE.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
> Bump up ZK session and connection timeout.

- README.md
- build.gradle
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- gradle/findbugs-exclude.xml
- kafka-cruise-control-start.sh
> Bump up Scala version to 2.12.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcher.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcherManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingFetcher.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/TrainingFetcher.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/BootstrapTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SamplingTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/TrainingTask.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- gradle.properties
This PR resolves #1253 and #1254.
> Enable broker metric collection during ongoing executions

- docs/wiki/Developer Guide/Build-the-cluster-workload-model.md
> Add missing wiki on building the cluster workload model

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokers.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java
> Share a common abstraction layer for all goal-based operation runnables.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
> Fix NPE while taking CC servlet out of service.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
> Fix missed broker failure detection/self-healing upon bootstrap.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailuresTest.java
> Fix NPE in BrokerFailures.toString

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
> Fix GOAL_VIOLATION detector getting stuck execution in GENERATING_PROPOSALS_FOR_EXECUTION state

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- docs/wiki/User Guide/Sensors.md
This PR resolves #1293.
-- Also updates the stale wiki on CC sensors.
> Add sensors to emit concurrency caps for partition and leadership reassignments

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ConcurrencyType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/AdminRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/AdminParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/UpdateConcurrencyAdjusterParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
- cruise-control/src/yaml/endpoints/admin.yaml
- cruise-control/src/yaml/responses/adminResult.yaml
> Add support to dynamically enable/disable concurrency adjuster

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
> Update min valid windows required to start self-healing with goals using resource history.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java
> Log uncaught exception in Thread.setDefaultUncaughtExceptionHandler

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/StopProposalResult.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR resolves #1307.
-- The correctness of execution has also been verified on a `Kafka 2.4` cluster with and w/o `stop_proposal_execution`.
> Eliminate inefficiencies in execution process.

- docs/wiki/User Guide/Configurations.md
- docs/wiki/User Guide/REST-APIs.md
This PR adds table of contents links to the Configuration and REST API wiki pages to make them easier to navigate.
> Navigational improvements to Configuration and REST API wiki pages

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
This PR resolves #1244.
* On clusters with >250 brokers this can still be an issue.
> Bump up ZK session and connection timeouts.

- README.md
This PR resolves https://github.com/linkedin/cruise-control/issues/890#issuecomment-682179808.
> Clarify the dependency folder path for Kafka release downloads

- cruise-control-client/cruisecontrolclient/client/CCParameter/SetOfChoicesParameter.py
- cruise-control-client/setup.py
> [ccclient-1.1.1] Extend support for anomaly detectors

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java
> Check entries value in partition load query to disallow negative values (#1351)

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailureDetector.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MaintenanceEventTopicReader.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicReplicationFactorAnomalyFinder.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/KafkaClusterStateRequest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterBrokerState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/CruiseControlIntegrationTestHarness.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManagerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/MaintenanceEventTopicReaderTest.java
> Adopt a shared AdminClient across selected CC components

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OfflineProposalGenerator.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
> Let implementations of OptimizationOptionsGenerator be configured with an AdminClient

- checkstyle/checkstyle.xml
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityInfo.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractMetricSampler.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcher.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/PreferredLeaderElectionGoalTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
This PR resolves #1370 and #1371.
> Add checkstyle rules to enforce ModifierOrder and RedundantModifier

- .circleci/config.yml
> Roll forward to Java 11.

- build.gradle
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgressTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/OperationFutureTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtAuthenticatorTest.java
This PR resolves #1376 and #1373.
> Bump up stale dependencies

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java
> Fix a bug that might cause invalid throttle replica list to be used

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
Under onlyMoveImmigrantReplicas check
> fix typo in GoalUtils.java

- kafka-cruise-control-start.sh
> Update stale scala version in start script

- CONTRIBUTING.md
- docs/code-style.xml
> Update guidelines for committers

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
The port of kafka may not be 9092 and should be determined according to the user's configuration.
> modify how to get kafka port

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/LowResourceUtilizationTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtilsTest.java
> Calculate balance lower bound for resource distribution lower bound with low utilization threshold

- cruise-control-client/cruisecontrolclient/client/Endpoint.py
- cruise-control-client/setup.py
> [ccclient-1.1.2] Add topic parameter in cruise-control-client to query the kafka_cluster_state endpoint

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- docs/wiki/User Guide/Sensors.md
> Add a sensor to emit topic count in cluster

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java
> Handle non-existent topic while setting/removing throttled replicas for a topic

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtilsTest.java
> Relax low resource utlization upper limit for resource distribution goals

- LICENSE
This PR resolves #1427 (to be merged in 2021).
Happy and **healthy** new year to Cruise Control community!
-- Wish you all well-balanced Kafka clusters :)
> Add 2021 to LICENSE

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
> Reset the provision status to ensure freshness for consecutive optimizations

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
> Prevent optimization failures with excluded brokers for replica move with replicas

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/ActionType.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingAction.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
> Remove REPLICA_ADDITION and REPLICA_DELETION

- build.gradle
> Update stale dependencies

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
> Reduce verbosity of CruiseControlMetricsReporterSampler log

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/AnalyzerConfig.java
This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR>.
> [MINOR] fix a typo

- docs/wiki/User Guide/REST-APIs.md
This PR resolves #1451.
The issue is not related to the title but mentioned in the discussion.
> Add 2-step verification information to REST-API docs

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlTest.java
> Report ongoing replica reassignments started by an external agent

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/CruiseControlUtils.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinder.java
- cruise-control-core/src/test/java/com/linkedin/cruisecontrol/CruiseControlUtilsTest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetails.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/holder/PartitionMetricSample.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ReviewResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
> Adopt ISO 8601 format with calendar date, hour, minute, and second

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusMetricSampler.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusMetricSamplerTest.java
> Handle topics with dot for Prometheus Sampler

- config/cruisecontrol.properties
Fixed description of network.outbound.low.utilization.threshold
> Fixed network.outbound.low.utilization.threshold

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposal.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionProposalTest.java
> Make CC inter-broker replica reassignments resilient against partitions with ISR set > replica set

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
> Prevent ResourceDistributionGoal from generating provision recommendations with a negative number of brokers to remove.

- docs/wiki/Troubleshooting.md
This PR resolves https://github.com/linkedin/cruise-control/issues/1472#issuecomment-785531222. 
Following up on the discussion on the above mentioned thread, the purpose of this guide is to help users debug common issues that might arise when deploying and running Cruise Control. The hope is that users will first read this guide for troubleshooting CC, and then create a new issue if they could not find a resolution there. This should help in reducing the number of duplicate issues as well.
> Add a Troubleshooting guide to the wiki

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
> Stop execution before shutting down Cruise Control

- checkstyle/checkstyle.xml
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/CruiseControlUtils.java
- cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/MinTopicLeadersPerBrokerGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetails.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyMetrics.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AbstractCruiseControlResponse.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/JsonResponseClass.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/JsonResponseExternalFields.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/JsonResponseField.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/LowResourceUtilizationTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/WebserverUrlPrefixConfigTest.java
> Ensure proper ordering/grouping of imports

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
This PR resolves #1521.
Notes
* Also fixes a bad debug-level log with incomplete logging -- i.e. just the disk capacity rather than all capacity.
> Avoid NPE due to misused rebalance_disk parameter

- README.md
> docs typo fix

- README.md
This PR resolves #1535. Additionally we could add more details to the troubleshooting guide.
> Add Known Compatibility Issues section to README

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizerResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
- cruise-control/src/yaml/responses/goalStatus.yaml
> Report optimization time of individual goals in OptimizationResult

- checkstyle/checkstyle.xml
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/CruiseControlUtils.java
- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregationResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/metricdefinition/KafkaMetricDef.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/SecurityProvider.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/LowResourceUtilizationTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/MaintenanceEventTopicReaderTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/MaintenancePlanSerdeTest.java
> Add CheckStyle rules for AtclauseOrder, AnonInnerLength, and AvoidDoubleBraceInitialization

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
> Copy through configuration for sasl.client.callback.handler.class in AdminClient

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/StopProposalParameters.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/StopProposalResult.java
- cruise-control/src/yaml/endpoints/stopProposalExecution.yaml
- docs/wiki/User Guide/REST-APIs.md
This PR is the first step to address #1461.
> Add capability to stop executions not started by Cruise Control

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/DefaultOptimizationOptionsGenerator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/yaml/endpoints/addBroker.yaml
- cruise-control/src/yaml/endpoints/fixOfflineReplicas.yaml
- cruise-control/src/yaml/endpoints/proposals.yaml
- cruise-control/src/yaml/endpoints/rebalance.yaml
- cruise-control/src/yaml/endpoints/removeBroker.yaml
- cruise-control/src/yaml/endpoints/topicConfiguration.yaml
- docs/wiki/User Guide/REST-APIs.md
> Set the default proposal generation speed to fast mode

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
> Fix throttler quota removal for in-progress tasks

- settings.gradle
> Fix publish failure due to NoSuchMethodError with Apache HttpClient

- README.md
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaTopicConfigProvider.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
- gradle.properties
- kafka-cruise-control-start.sh
This PR resolves #1586 and upgrades to Scala 2.13.6.
> Upgrade to Scala 2.13

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaAdminTopicConfigProvider.java
> Ensure that config entry has non-null values in KafkaAdminTopicConfig Provider

- docs/wiki/User Guide/REST-APIs.md
> Update REST-API user guide for CC version with stop_external_agent flag

- README.md
> Update README regarding Kafka 2.8 support

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtilsTest.java
> Add retry logic for creation of all CC topics

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaTopicConfigProvider.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
> Replace deprecated JavaConversions with JavaConverters

- checkstyle/checkstyle.xml
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaAnomaly.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AlertaSelfHealingNotifier.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/DiskStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AdminResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/BootstrapResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/PartitionLoadState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/PauseSamplingResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ProgressResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ResponseUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ResumeSamplingResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ReviewResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/RightsizeResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/StopProposalResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/TrainResult.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BrokerStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/SingleBrokerStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/SingleHostStats.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolverTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletEndpointTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
> Enhance CheckStyle Configuration

- docs/wiki/User Guide/Sensors.md
Hi,
I think that it worth mentioning in the Wiki that you can easily enable JMX in order to collect Cruise Control metrics.
Thanks, and keep up the good work! 🥇
> Mention JMX in Sensors.md

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java
> Handle metrics reporter exceptions while getting CPU metric.

- build.gradle
> Use the maven-publish plugin instead of the removed maven

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ProvisionerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/RightsizeResult.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/PartitionProvisionerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtilsTest.java
> Indicate ignored topics for partition count increase in rightsizing requests

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java
> Clarify the exception message in ReplicaCapacityGoal

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
> Fix error when trying to disable self-healing

- build.gradle
- cruise-control-core/src/test/resources/log4j.properties
- cruise-control-metrics-reporter/src/test/resources/log4j.properties
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java
- cruise-control/src/test/resources/log4j.properties
> Add ZK TLS support with properties file and modify broker failure detection

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionState.java
> Shorten kafka cluster state URP header length

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- docs/wiki/User Guide/Sensors.md
> Add a sensor to keep track of the automated rightsizing rate

- cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java
> Bump up timeout in testTopicAnomalyFinder

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/LowResourceUtilizationTest.java
> Improve efficiency of goal optimization process

- .circleci/config.yml
This PR temporarily addresses #1748.
> Temporary CI timeout increase to work around long integration test

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/strategy/AbstractReplicaMovementStrategy.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/strategy/ReplicaMovementStrategy.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
This PR introduces a new broker `Comparator`.
Pick the broker with the prioritized task first resolves #1745. 
If tie, pick the broker with the larger task set first resolves #1744.
> Pick broker to submit task according to task priority and task set size

- LICENSE
This PR resolves #1762.
Happy and **healthy** new year to Cruise Control community!
-- Wish you all well-balanced, self-healing Kafka clusters :)
> Add 2022 to LICENSE

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
This PR resolves #1768.
After profiling a running CC instance, we noticed that the majority of the time is spent on iterating through `SortedSet _interPartMoveBrokerIds`, which is introduced in #1746.
The reason for spending so much time is due to an element leak in this TreeSet.
We remove involved brokers in `_interPartMoveBrokerIds` after we change the broker comparison order (with changing first tasks on involved brokers potentially). This makes `remove()` can't find the element to remove by traversing the tree with the new comparison order. In some cases, TreeSet grows significantly with duplicate brokers, which increases overall iterating time.
I have eyeballed the test to make sure only add brokers with no tasks are skipped. Other add and remove operations always modify …
> Fix leaked interPartMoveBrokerIds

- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtilsTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyAuthorizationServiceTest.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginServiceTest.java
This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR>1408
> fix: Adding missing EasyMock.verify calls #1414

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlApp.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/SslConnectionIntegrationTest.java
> Ability to configure HSTS response headers

- build.gradle
> Remove unused com.101tec:zkclient dependency

- config/cruisecontrol.properties
> Remove unused property from cruisecontrol.properties

- build.gradle
Pulling changes from https://github.com/linkedin/cruise-control/pull/1811 into kafka_2_0_to_2_3 branch
This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR>.
> Pin jackson for CVE-2020-36518

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BrokerStats.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/response/BrokerStatsTest.java
> Update the numCore type to double in BasicStats

- cruise-control/src/yaml/responses/brokerStats.yaml
> Update NumCore type in brokerStats.yaml

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/InvalidPrometheusResultException.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusAdapter.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusMetricSampler.java
This PR fixes minor logging string formatting. In Prometheus sampler flow there are places where stack trace was omitted.
> Fix minor logging issues

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java
> Make sure the provision response is always RIGHT_SIZED if it is not OVER_PROVISIONED

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingConstraint.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetFileResolver.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetFileResolverTest.java
This PR resolves #1880.
@mohitpali FYI. I think this logging is not intentional brought in your PR #1809 . Please correct me if I'm wrong.
> Mute KafkaCruiseControlConfig logs during anomaly detection

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
This PR renames the getGoalsByPriority to getDefaultGoalsByPriority
> Rename the getGoalsByPriority to getDefaultGoalsByPriority

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AbstractBrokerFailureDetector.java
> Fix failedBrokers.txt permissions

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
> Future-proof for Kafka 3.3 for KafkaYammerMetrics class name changes

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
> Fix leader replica cpu util when leader egress is zero

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
> Add fixability metrics to GoalOptimizer

- cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapacityViolationIntegrationTest.java
- cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java
> Adjust the flaky integration test timeout to higher value

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterBrokerState.java
> Log broker-set resolution error only when BrokerSetAwareGoal is in default goal list

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ProgressResult.java
This PR resolves #1948 .
The parent class has the default method which returns code 200. This is not correct for ProgressResult, as it should return 202.
> Fix the response code to 202 for in-progress request

- cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapacityViolationIntegrationTest.java
- cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlVertxApp.java
This PR resolves https://github.com/linkedin/cruise-control/issues/1662
Hi @CCisGG, thank you for your patience. In the last couple days I was experimenting/debugging the tests. I came to a conclusion, that this is not a performance issue, it was something with the port of the Vertx app in the test cases.
This is a successful test run on Circle Ci (the workflow is a bit different, but it runs the ITs) : https://app.circleci.com/pipelines/github/kismob/cruise-control/48/workflows/d28e46a3-3ef7-43ca-964f-141f18bc3fe9/jobs/92
I hope it will finally resolve this issue.
> Fix and enable integration tests

- gradle.properties
> Update Netty dependency to 4.1.89.Final (#1969)

- gradle.properties
This reverts commit cf5f0377f204a174d5e77c32b7be562872dbeb2f.
> Revert "Update Netty dependency to 4.1.89.Final (#1969) (#1970)"

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR resolves #1979 .
Basically executor will reduce this executionProgressCheckIntervalMs if all tasks in a batch are completed within one check interval. Eventually it will hit minExecutionProgressCheckIntervalMs.
> Dynamically adjust the executionProgressCheckIntervalMs based on execution status

- gradle.properties
This reverts commit 11ea877755ac5d006a48cb45762131aa960a4146.
This PR resolves #1969 .
> Revert "Revert "Update Netty dependency to 4.1.89.Final (#1969) (#1970)" (#1984)"

- CONTRIBUTING.md
> Use relative path for CONTRIBUTING.md links

- build.gradle
> Upgrade org.json to 20230227 due to CVE-2022-45688

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- docs/wiki/User Guide/Sensors.md
> Add metrics for dead brokers

- build.gradle
Update packages to also update transitive dependency on vulnerable snakeyaml
This PR resolves #2035
> Update dependencies for swagger and jackson

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveDisksRunnable.java
Update RemoveDisksRunnable to use the latest `KafkaCruiseControl.executeProposals` API.
> Fix release/PR build

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlServletApp.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java
> Issue 2011 - fix SPNEGO/Kerberos Header too large (HTTP 431)

- build.gradle
> Upgrade org.json to 20231013+ due to CVE-2023-5072

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
- docs/wiki/User Guide/Sensors.md
Add anomaly detect-to-fix-complete-timer metrics which measures the time from anomaly being detected to self-healing completed.
> Add anomaly detect-to-fix-complete-timer metrics

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
This PR adds operation logs for the task execution time.
> Add operation log for execution time.

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Consider task that involves deleted topic being completed when deciding whether to increase or decrease executionProgressCheckIntervalMs dynamically.
> Consider task with deleted topic as completed for updating  executionProgressCheckIntervalMs

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
> Fix SASL/OAUTHBEARER configuration

- build.gradle
- gradle.properties
This PR is addressing the following CVEs:
CVE-2023-44487
CVE-2023-2976
CVE-2020-8908
> Guava, jetty cve fixes, netty version unifying

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
> Update _sortedReplicas correctly

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java
> Fix slow task calculation bug

- cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
> Add loggings for partition load aggregation

- cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
> Example Add kafka send failure exception logs 

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- Provide partition movement details in`OngoingExecutionException` exception message.
- Having partition movement details is handy for troubleshooting in cases when partition movements are ongoing for a long time, providing necessary details for potential mitigation.
> Add partition movement details to `OngoingExecutionException` exception

- build.gradle
Signed-off-by: Aswin A <aswin6303@gmail.com>
This commit addresses a DoS vulnerability in
SnappyInputStream due to missing chunk size validation.
This PR resolves #https://github.com/linkedin/cruise-control/issues/2157
> fix: Fix DoS vulnerability in SnappyInputStream(CVE-2023-43642)

- gradle.properties
> Upgrade vertx to 4.5.8

- cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Remove unused variable in `KafkaSampleStore` class.
> TRIVIAL: remove unused _skipSampleStoreTopicRackAwarenessCheck

- docs/pull_request_template.md
Why:  Improve PR quality and review-ability.
What:  modifies current PR template to be structured and require more details when submitting PRs.
PR must come with sufficient details to address or explain the issue.
PR template only requires link to the issue:
```
This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR>.
```
1. either create a new PR or
2. see [the current template](https://github.com/linkedin/cruise-control/blob/c5545ef04618b5b42290edda2ee63eb6bfa2e1a6/docs/pull_request_template.md)
People voluntarily provide additional details
- n/a
> new PR template

- LICENSE
Update license to reflect the latest status
> Update license to reflect the latest status
