linkedin/cruise-control

.circleci/config.yml, .gitignore
This change just runs tests, but does not publish the build which requires some additional configuration and testing.
=> CircleCI testing.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java
There is a bug in MetricSampleAggregator that may result in the `_snapshotCollectionInProgress` counter to be negative, which will cause the aggregator not to evict the old snapshots windows.
=> Fix MetricSampleAggregator eviction

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/Resource.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
The patch does the following:
1. check whether old windows should be evicted on every sampling instead of waiting for the next window to be rolled out.
2. Use a adaptive epsilon in the double comparison. This avoids false failure on the big disk utilization.
=> Improve MetricSampleAggregator and sanity check stability

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricCompletenessChecker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java
MetricSampleAggregator has a ConcurrentHashMap for each snapshot window. Currently the key in those ConcurrentHashMaps are different TopicPartition instances for the same partition, which takes a lot of memory. This patch uses an identity map to ensure that there is only one TopicPartition instance for the same partition.
=> Add an identity map for TopicPartition in the metric aggregator to reduce memory consumption

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoals.java
The test was failing because the float to double conversion. If we move a little tiny thing from one broker to another. The variance may be actually become worse due to the float to double conversion. Change the test to compare the sqrt of variance and use the NW_IN epsilon. Ran the test over 100 times and it seems to work.
=> Fix the flaky RandomGoalTest

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/Resource.java
We see sometimes the cluster model sanity check fails on the large clusters. This is caused by double/float conversion. When there are a lot conversions, the precision error accumulates. Change the epsilon percent from 0.01% to 0.1% to avoid fail the sanity check.
=> Change comparison epsilon percent to 0.1% for large clusters.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/MetricCompletenessChecker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomSelfHealingTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/RandomCluster.java
A few bug fixes:
1. Fix an NPE in the MetricCompletenessChecker when topic deletion happens.
2. Correctly handle the topic names which contain ".". In that case, the metrics reporter will replace the "." with "_" in the topic name.
3. Fix the capacity check when removing brokers.
4. Fix the RandomSelfHealingTest
One interface change: Added with_available_valid_windows and with_available_valid_partitions options to add/remove brokers
Default behavior change:
1. By default the precomputing will use with_available_valid_windows now instead of with_available_valid_partitions.
2. If there is not sufficent data, the /proposals and /rebalance REST API will now follow the order of
a. with_avaialble_valid_windows
b. with_ready_goals
c. with_available_valid_partitions
=> A few bug fixes and improvements.

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
1. Removed a sanity check on the RackAwareCapacityGoal. As long as the end result meets the goal, we should let the goal to run.
2. Fixed a configuration in the cruisecontrol.properties.
3. Revert back to always call capacity resolver even if the broker is dead. Because the host level resource capacity relies on the per broker resource capacity as of now.
=> Make the RackAwareCapacityGoal more robust. Fix cruisecontrol.properties.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
Also fix potential frequent logging in GoalOptimizer.
=> Disable self-healing by default in the SelfHealingNotifier.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
We are having more and more goals now. We are holding the lock for too long. This patch release the lock between each goal to avoid holding it for all the goals.
=> Avoid holding the lock for too long when running goal violation detection

kafka-cruise-control-start.sh
Debug must be explicitly enabled by `KAFKA_DEBUG ` environment variable. Most likely this has been mistakenly enabled by https://github.com/linkedin/cruise-control/commit/de2b67275bee8af48068ded446efcb2aa580c6e2
=> Disable Debug mode by default

README.md, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
Currently CC does not set the cleanup policy for the topics that it creates – i.e. __KafkaCruiseControlModelTrainingSamples, __KafkaCruiseControlPartitionMetricSamples.
This patch aims to set the value of this config to `delete` inside CC.
This patch fixes the following issue: https://github.com/linkedin/cruise-control/issues/76
=> Support for setting cleanup policy for CC generated topics

README.md, config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingConstraint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/DeterministicClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomGoalTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomSelfHealingTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java
_ReplicaCapacityGoal_ is a hard goal.
It ensures that the maximum number of replicas per broker is under the specified maximum limit controlled by `max.replicas.per.broker`
=> Add Replica Capacity Goal.

kafka-cruise-control-start.sh
Fixes the issue https://github.com/linkedin/cruise-control/issues/91.
=> Fix broken path in Cruise Control start script to copy jars.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java
This enables a capacity resolver to estimate the capacity of the nodes, for which the capacity retrieval has failed (if supported by the capacity resolver). If the call to the `capacityForBroker` fails on the invocation with the first node as the parameter, the capacity resolver would be unable to estimate the remaining nodes; hence, might throw an exception. Node shuffling decreases the likelihood of such failures on consecutive user requests.
=> Shuffle nodes before getting their capacity from the capacity resolver

build.gradle, config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Partition.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomSelfHealingTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDeterministicClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerExcludedTopicsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerOptimizationVerifier.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterExpDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterExpDistRebalanceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterLinearDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterLinearDistRebalanceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterUniformDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomClusterUniformDistRebalanceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerRandomSelfHealingTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
* Add a goal that combines the even balancing action of kafka-assigner and rack-awareness. 
* Fix self-healing bug in ReplicaCapacityGoal.
* Enable printing the stack trace of a failed test without waiting until all the tests are completed.
=> Add Kafka-Assigner Even Rack-Aware Goal.

cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/RandomCluster.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java
The repeated tests of CC may generate clusters with varying load at each execution due to missing resource utilization seeds in random cluster generation.
This patch stabilizes the random load generation by providing predetermined seeds.
=> Add seeds for random load generation.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/ModelCompletenessRequirements.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
* Fix `proposals` response to clarify the covered partitions and satisfied goals with no proposal generation.
* Fix `verbose state` response to clarify required number of windows.
=> Clarify naming in servlet responses.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
This patch:
* Adds the version field to JSON responses. (See https://github.com/linkedin/cruise-control/issues/107)
* Adds a default partition_load resource in case the user does not provide one.
* Standardize servlet response format (See https://github.com/linkedin/cruise-control/issues/108)
=> Add version field to JSON responses.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/resources/log4j.properties
Change the executor to wait for the tasks to finish during manual stop.
The rollback can not be done until KAFKA-6304 is in place.
=> Clean up the executor logic and wait for the tasks to finish during stop.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Identifies the occurrence of cases mentioned in Issue https://github.com/linkedin/cruise-control/issues/155.
=> Detect if Kafka cluster is reporting no alive brokers before creating sample store topics.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ViolationUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
When self healing is enabled, if the anomaly detector fix attempt fails due to (1) `LOADING` or `BOOTSTRAPPING` `loadMonitorTaskRunnerState` or (2) being unable to meet the model completeness requirements, the `IllegalArgumentException` thrown by the goal optimizer is not handled.
This patch catches the exception and logs it in warn level. These warnings are expected to be transient -- i.e. when the state is `RUNNING` and the model completeness is met upon sufficient data collection.
=> Handle anomaly detector goal fix exception.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/internals/BrokerAndSortedReplicas.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoalTest.java
1. Avoid unnecessary sort of the replicas in the brokers.
2. Use TreeSet instead of implementing binary search on list.
3. Speed up the test by avoid unnecessary sort. After the change the test time reduced from 20 min to 11 min.
=> Simplifying the KafkaAssignerDiskUsageDistributionGoal logic.

README.md
Current implementation relies on replicas list returned from a broker to have the same order as in zookeeper.
But due to https://issues.apache.org/jira/browse/KAFKA-5329 it's not guaranteed in Kafka < 0.11.0.0.
As an alternative we can change the implementation to not rely on the specific followers order.
=> Fix the compatibility version to 0.11.0.0

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlannerTest.java
Status tracking for leadership movements for the number of finished tasks, total tasks, and details of each pending task (in verbose mode).
=> Add status tracking for leadership movement.

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorState.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValues.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingFetcher.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
1. When precomputing thread is set to 0, /proposals may stuck.
2. Fixed the validity update in RawValues at the edge.
3. The KafkaSampleStore producer memory.buffer should be set to at least BATCH_SIZE * NUM_PARTITIONS
4. Fixed completeness cache in MetricSampleAggregator.
=> Fix a few bugs:

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java
This fix enables CC to identify attempts to create brokers with null capacity -- e.g. as it is potentially the case in issue-https://github.com/linkedin/cruise-control/issues/214.
=> Add sanity check against attempts to create a broker with null capacity.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/internals/BrokerAndSortedReplicas.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java
This patch fixes potential errors due to getting 0 disk capacity from capacity resolver while executing `KafkaAssignerDiskUsageDistributionGoal`.
```
Caused by: java.lang.IllegalArgumentException: fromKey > toKey
at java.util.TreeMap$NavigableSubMap.<init>(TreeMap.java:1368)
at java.util.TreeMap$AscendingSubMap.<init>(TreeMap.java:1855)
at java.util.TreeMap.subMap(TreeMap.java:913)
at java.util.TreeSet.subSet(TreeSet.java:325)
at com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal.findReplicaToSwapWith(KafkaAssignerDiskUsageDistributionGoal.java:375)
at com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal.swapReplicas(KafkaAssignerDiskUsageDistributionGoal.java:332)
at …
```
=> Handle replica wrapper comparison with non-positive disk capacity and with MAX and MIN_REPLICA.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java
If, for example, the load monitor is in `SAMPLING` state, an execution request fails due to unhandled exception while pausing the load monitor. This patch fixes this issue.
=> Ensure that the temporary states in the load monitor does not block execution.

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
This config sets the number of times that the same cluster model is optimized with the same set of goals by a given precomputation thread. We used to need this config because the Analyzer component was not deterministic -- i.e. used to generate different optimizations under the same circumstances. However, this is no longer the case; hence, we can safely remove this config to avoid redundant loss of performance when this config is set to a value greater than 1 -- not that the default value was `10`.
=> Remove the redundant config max.proposal.candidates.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaClusterState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
1. fix the issue reported in ticket https://github.com/linkedin/cruise-control/issues/223 , add leader replica count per broker information in JSON response
2. fix get bootstrap/train JSON response,  remove traceStack field and rename errorMessage to message in normal response
3. fix kafka_cluster_state JSON response, increase readability of some fields
4. fix get load/partition_load JSON response reported in ticket https://github.com/linkedin/cruise-control/issues/263 . remove granularity parameter for get load request; add topic and partition parameter for get partition_load request. the topic parameter supports filtering partition based on matching a regular expression. the partition parameter supports filtering partition based on specific partition number or a partition number range …
=> Fix JSON response for multiple endpoints

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricValues.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ReplicaSortFunctionFactory.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ReplicaWrapper.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasTest.java
This is the first part of abstract resource distribution goal. The patch adds the support of 
caching the sorted replicas in the cluster model. This will be used for replica search in later patches.
Two follow up patches will be submitted:
1. A patch adds a generic replica search algorithm and flow.
2. the abstract metric distribution goal based on (1).
=> Add caching to the sorted replicas in the cluster model.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AddBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DecommissionBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/RebalanceRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/257.
=> Add parameters to set concurrent_partition_movements_per_broker and concurrent_leader_movements on the fly.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
In addition to provide CPU/DISK/NW_IN/NW_OUT information to reflect the partition load in partition_load endpoint,  the patch also provide the MESSAGE_IN information. the information shows for both JSON and regular response.
=> add partition message rate information to partition_load endpoint

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlState.java
* Return all `substates` in the `state` endpoint if `substates` is empty.
* Fix plain text state response for executor and analyzer substates.
=> Fix state endpoint response with substates.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetClusterModelInRangeRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
* For better flexibility of specifying the completeness requirement during cluster model generation,  add min_valid_partition_ratio to partition_load endpoint to set the completeness requirement on the fly.  
* Another change is when this parameter is missing in request, instead of using the hard code value(0.98) use the value set via CC config parameter `min.valid.partition.ratio`
=> Add min_valid_partition_ratio parameter to partition_load endpoint

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationFuture.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/EndPoint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManagerTest.java
Add following metrics
1. timer to trace the session avg/max life time
2. meter to trace the rate session manager fails new session creation due to capacity limit(already have 5 ongoing sessions)
3. timer per endpoint to trace the avg execution time for requests routed to each endpoint
4. meter per endpoint to trace the rate each endpoint receives new request
=> Add sensors to track the session lifetime and request execution time

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/WindowState.java, cruise-control-core/src/test/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
When `_minValidEntityRatio` in `AggregationOptions` is set to zero, `MetricSampleAggregator` will take window with zero valid entity as valid window in its `completeness()` and `aggregate()` method. At the same time, valid entity are collect as **entities which are valid in all valid windows**. This result in a corner scenario that if `_minValidEntityRatio` is set to zero and there happens to be one or more window with zero valid entity,  there will be zero valid entity in `MetricSampleAggregationResult`, which is used in `ClusterModel`.
One Cruise Control client visible case will be that client make a request to `partition_load` endpoint with parameter `min_valid_partition_ratio` set to 0. If in one window in Cruise Control's sample history has zero valid entity( can happen if Kafka …
=> Fix acceptance of window with zero valid entity as valid window in MetricSampleAggregator

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AddBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DecommissionBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/DemoteBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetOptimizationProposalsRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/RebalanceRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/EndPoint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
`topics.excluded.from.partition.movement` parameter enables users to specify the topics to exclude from partition movements -- unless the replica from the excluded topic is offline. However, users cannot specify the value of this config dynamically.
This patch adds `EXCLUDED_TOPICS` parameter to the following endpoints to dynamically specify the topics to exclude from replica movements:
- `PROPOSALS`,
- `ADD_BROKER`,
- `REMOVE_BROKER`,
- `REBALANCE`,
- `DEMOTE`
=> Add parameter to dynamically specify the topics to exclude from replica movements.

README.md
New jar files are being built with `cruise-control-metrics-reporter-A.B.C.jar` instead of `cruise-control-metrics-reporter.jar`, updated the doc to reflect this.
=> changed jar file path

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/EndPoint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
CruiseControl used sessions to manage async operations from users and
limited it by the number of active sessions.
This commit introduces the concept of UserTaskManager (replaces SessionManager).
It's responsible for managing active tasks using User-Task-ID defined in
the HTTP request/response header.
HttpSessions can still be used to fetch the status of an asynchronous operation
but it can be overridden by adding the User-Task-Id as the request header.
Every asynchronous request will return the User-Task-Id in the response headers that
can be used by the client to fetch the asynchronous operation status.
A new Http request is added to report the status active tasks that are in
progress.
=> Support a user-task based management to replace session based managment.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Currently `skip_hard_goal_check` parameter on `add_broker`, `remove_broker`, and `rebalance` endpoints must be set to `true` to avoid hard goal enforcement. 
For `kafka_assigner` mode,  ` skip_hard_goal_check=true` should be true by default.
=> Disable hard goal enforcement in kafka assigner mode.

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/ReadOnlyKafkaSampleStore.java
Remove the config of pluggable component from centralized config definition in KafkaCruiseControlConfig so that user can have their own class implementation and customized config of these pluggable component and plug in to use with Cruise Control.
=> Add several configs to KafkaCruiseControlConfig and improve its usage in reflective created object.

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/test/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java
There is bug in `MetricSampleAggregator` that the maximal number window can be rolled out is ceilinged by maximal number of window kept in memory. This cause issue in scenario where sampling is resumed after long time pause and more window needs to be rolled out. In case `SamplingTask` will keep failing and Cruise Control is hang(unable to execute any operation).
=> Fix the bug in MetricSampleAggregator sample window rolling out

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Previously, line 197 returns the string ending in literal "%n".
This results in output like  
```
java.lang.IllegalStateException: Allow capacity estimation or fix dependencies to capture broker capacities.%nBroker: 33882
```
It appears, however, that the intention is to use an OS-independent newline character, rather than %n literal.
Accordingly, surround the string containing "%n" in String.format() method, to return an OS-independent newline character.
=> Use newline rather than literal %n

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Currently we check the user provided broker ID after cluster model is generated, which is a expensive process. The patch moves this check before cluster model generation, thus fail faster for broker ids missing from the cluster in remove broker request.
=> Improve the detection of wrong broker ID in decommission broker request.

config/capacityJBOD.json, config/cruisecontrol.properties, config/log4j.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaClusterState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityInfo.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/TopicConfigProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolverTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/resources/testCapacityConfigJBOD.json
* Add logDir information to cluster model and kafka cluster state.
* Fix a typo that prevents printing to `PublicAccessLogger`.
=> Add logDir information to cluster model and kafka cluster state.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionTarget.java
* Ensure that Potential NwOut Goal uses the capacity of the correct broker -- i.e. destination, not the source.
* Ensure correct destination broker id while updating the global sorted broker set in Replica Distribution Goal.
* Ensure correct warm credit adjustment for TopicReplica Distribution Goal.
=> Fix Replica Distribution, Potential NwOut, and TopicReplica Distribution Goals.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
1. fix the issue in user_tasks endpoint that the return message does not reserve enough space for user identity field(which can be IPv6 address)
2.remove the invalid broker checking in remove_broker endpoint to handle the scenario that we want to use Cruise Control to remove a broker which has already died(since now shows in latest metadata)
3.fix the issue in proposals endpoint that sometimes the returned operation progress message does not reflect what is going on inside Cruise Control.
=> Fix issues in proposals/remove_broker/user_tasks

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/DeterministicClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalShuffleTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterExpDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterLinearDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterUniformDistNewBrokerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomGoalTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomSelfHealingTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/363.
In endpoints that receive `goals` as input (e.g. `proposals`, `add_broker`, `remove_broker`, `rebalance`), if the following conditions are satisfied:
1) user does not provide `goals` parameter,
2) a strict subset of default goals are ready, but this strict subset excludes some `hard.goals` defined via `cruiescontrol.properties`, and
3) `NumValidWindows` is 0 (can be checked via `state` endpoint).
Then, in an effort to run the requested operation (such as `remove_broker`), Cruise Control implicitly attempts to execute with the ready goals -- i.e. a strict subset of default goals. This creates 3 issues: 
1. Lack of control over whether all the default goals or a subset of these goals are going to be used.
2. Lack of …
=> Add use_ready_default_goals parameter to enable user to control the use of a subset of default goals that are ready.

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValues.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaBrokerMetricSampleAggregator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
Several bug fix and performance improvement in this path.
1. fix the bug in creating the broker metric sample topic(wrong config get picked up, result in wrong retention time of the topic)
2. fix the bug in loading partition/broker sample metric from corresponding topic(seek to the wrong beginning offset, result in doubling the Cruise Control boot up time)
3. improve the loading logic to reduce the contention between thread(to acquire the some lock) and burning CPU cycle(due to too short poll time)
4. improve the logging in sample loading process,  to help debugging if things goes wrong
=> Improve sample loading efficiency in Cruise Control booting up process.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java
This patch adds a hard-coded timeout for the per broker swap operations in resource distribution goals.
Future patches will remove this hardcoded value and make it configurable.
=> Add per broker swap timeout for resource distribution goals.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
Explicit calls to `closeSession()` has become redundant after the addition of `UserTaskManager`.
=> Remove UserTaskManager#closeSession().

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
When dynamically setting metric.reporters to use cruise control, the Kafka brokers refuse to reload the new config because the 'port' property is actually an Integer which doesn't get properly cast to a string.
=> Fixes crash when using dynamic reconfig

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java
fix for issue[404](https://github.com/linkedin/cruise-control/issues/404)
=> Fix the bug that Cruise Control returns in accurate valid partition ratio in State endpoint.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcherManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SamplingTask.java
The fix added flag to indicate there's a pending Execution request. The LoadMonitor will not kick off consecutive sampling if it sees the flag is set. 
It's noticed that if MetadataClient.refreshMetadata() timeout (KafkaCruiseControlConfig.METADATA_MAX_AGE_CONFIG) is longer than sampling period for SamplingTask (KafkaCruiseControlConfig.METRIC_SAMPLING_INTERVAL_MS_CONFIG ). We need to make sure the timeout is no longer than the sampling period because the code will anyways throw TimeoutException if execution takes longer than sampling period. There's no need to wait longer than necessary. 
-- Fixes the issue https://github.com/linkedin/cruise-control/issues/397.
=> Fix for Executor state would stuck at STARTING_EXECUTION if CC metric sampler is stuck at SAMPLING state

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/ModelGeneration.java
The value of `_cachedBrokerLoadStats` and ` _cachedBrokerLoadGeneration` should be protected while reading them.
=> Fix the concurrency bug in cached broker load stats retrieval.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
Fixes issues including https://github.com/linkedin/cruise-control/issues/325, https://github.com/linkedin/cruise-control/issues/318, https://github.com/linkedin/cruise-control/issues/255, https://github.com/linkedin/cruise-control/issues/238.
Thanks to @craynic for helping us resolve the issue by sharing `TRACE`-level logs.
=> Handle topics with dots to fix WARNs regarding missing topic and partition metrics.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/449.
=> Allow missing log flush time 50th and 999th percentiles for broker sample creation.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/457.
=> Fix improper clearing of the completed execution stats in executor substate.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
In the scenario where there is no traffic for certain broker, the Cruise Control reporter on this broker will not report `BROKER_PRODUCE_REQUEST_RATE` and `BROKER_CONSUMER_FETCH_REQUEST_RATE` metrics and the metric processing logic inside Cruise Control will report warning like
` [MetricFetcher-0] [kafka-cruise-control] [] Skip generating broker metric sample for broker xxxx because the following required metrics are missing [BROKER_PRODUCE_REQUEST_RATE, BROKER_CONSUMER_FETCH_REQUEST_RATE]`
Given the behavior of reporter is reasonable here, this patch make these two broker metric optional.
=> Allow missing broker produce request rate and consumer fetch request rate metrics from reporter

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Patch for issue [455](https://github.com/linkedin/cruise-control/issues/451).
Improvement made to goal violation anomaly detection and auto-fixing logic.
* remove caching unneeded proposal for each goal violation
* distinguish fixable and unfixable goal violation and handle them differently
* filter all the support goal to check based on readiness of each goal
=> Improve goal violation anomaly detection and auto-fixing logic.

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletDataFromTest.java
Adds the feature explained in https://github.com/linkedin/cruise-control/issues/476.
=> Keep and expose a history of recently removed brokers in the executor substate of the state endpoint.

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/test/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorTest.java, cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
Addresses the issue https://github.com/linkedin/cruise-control/issues/491.
=> Avoid redundant generation bump up in retainEntityGroup.

cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala
Addresses a concurrency issue due to https://github.com/linkedin/cruise-control/issues/496.
=> Preserve desired partition reassignment concurrency in Kafka 1.1.0+ (Part-2).

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/503.
=> Increase the default config values for history retention time of removal and demotion.

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
I use this code to create topic "__CruiseControlMetrics" in cruisecontrolmetricsreporter.
It can deploy the topic with parameterized config in case of a non auto creation topic Cluster.
=> Add the possibility to create the metric reporter topic at launch

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/513.
=> Increase the default config value for completed user task retention time

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/525.
=> Make exclusion of recently removed/demoted brokers configurable for broker failure self-healing.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinder.java
Currently if the config `metric.anomaly.analyzer.metrics` is set to empty string, the default list of metric anomaly will be picked up, which may not be what we want in some case. 
This patch changes `KafkaMetricAnomalyFinder`'s behavior to:
if (`metric.anomaly.analyzer.metrics` is null)
pick up default list
else if(`metric.anomaly.analyzer.metrics` is an empty string)
just ignore all metric anomaly
else
pick up what is specified in this config
=> Make Cruise Control ignore all metric anomaly if metric.anomaly.analyzer.metrics is set to empty string.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/538.
=> Avoid IllegalStateException upon invalidating a session in a SessionKey that has already been invalidated for another SessionKey.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetClusterModelInRangeRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/540.
=> Ensure that partition_load endpoint returns the partitions ordered by peak load if requested so.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java
Fixes the issue https://github.com/linkedin/cruise-control/issues/555.
=> Fail fast if there is an ongoing execution and the user attempts to start a new execution.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/CruiseControlStateParameters.java
`verbose` is present twice in the docstring for this class.
Accordingly, remove the last occurrence of this parameter from the docstring.
=> Remove redundant verbose parameter

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java
Fix for issue [609](https://github.com/linkedin/cruise-control/issues/609)
=> Make replica order of partitions returned in kafka_cluster_state response be consistent with Kafka's metadata.

build.gradle, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackMessage.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifier.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackMessageTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifierTest.java
Desc:
The self-healing and anomaly detected is the crown feature of Cruise Control, but often the actions taken by Cruise Control provide less visibility to its operation. Adding a slack notification for all the anomaly detection and self-healing will increase Cruise control visibility.
Changelog:
The SlackSelfHealingNotifier extends SelfHealingNotifier and merely override the alerts method to send the notification to Slack.
Configuration:
The following property requires to be configured on cruisecontrol.properties 
1. slack.self.healing.notifier.webhook (Required)
(Slack webhook URL) Ref:https://api.slack.com/incoming-webhooks
2. slack.self.healing.notifier.channel (Required)
(Slack channel name to send the alert, (e.g) #alerts-cruise-control
3. slack.self.healing.notifier.user …
=> Add slack notification

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/KafkaNetworkClientProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/NetworkClientProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/634.
=> Add a pluggable NetworkClientProvider to create network clients supporting different Kafka client versions

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ReviewResult.java
When two step verification is enabled,  request to all POST endpoint and review_board GET point will get error response.
`Error processing POST/GET request 'endpoint' due to: 'd != java.lang.String'`
The root cause is a formatting conversion bug in `ReviewResult`.
=> Fix the format conversion issue in ReviewResult response.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/645.
=> Increase the default value of TOPIC_REPLICA_COUNT_BALANCE_THRESHOLD_CONFIG to 3.00 to prevent excessive violations of Topic Replica Distribution Goal.

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
This pull request should fix support of non-GSSAPI SASL authentication mechanisms in 2.X
Related issue: #583
=> Inherit sasl.mechanism and sasl.jaas.config for AdminClient

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Fix a bug from cherry-picking the [patch 604](https://github.com/linkedin/cruise-control/pull/604) from master branch.
=> Fix the bug which may cause infinite loop when increasing sample topic's replication factor.

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/BalancingConstraint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PreferredLeaderElectionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerEvenRackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetProposalsRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/RebalanceRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/654.
=> Add a configurable multiplier to adjust the balance threshold of distribution goals during detection and fixing of goal violations

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ResponseUtils.java
Per conversation in Slack channel, extra header field is needed for CORS to work.
=> Add header field Access-Control-Allow-Credentials in GET/POST response e if CORS is enabled.

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/685.
=> Remove the use of deprecated org.apache.kafka.common.Metric API.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java
Fix for [issue 687](https://github.com/linkedin/cruise-control/issues/687)
=> Fix the miscount of number of skipped brokers in aggregating raw metrics into broker metric samples.

config/cruisecontrol.properties, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/CruiseControlMetric.java, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/NoopSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/ReadOnlyKafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingFetcher.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/TrainingFetcher.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/693.
=> Make CruiseControlMetricsReporterSampler consumer use assign() rather than subscribe() to avoid consumer rebalance coordination overhead.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
This adds `ssl.endpoint.identification.algorithm` to the configuration options that Cruise Control respects. This is particularly useful for Kafka 2.X clusters that have been upgraded from Kafka 1.X and are relying on setting the option to match the older default.
=> Respect ssl.endpoint.identification.algorithm

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcher.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/708.
=> Prevent metrics reporter sampler from generating NPE when it fails to retrieve offsets for partitions to consume.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/706.
=> Ensure that reconnect.backoff.ms configuration applied to metric sampler consumer and sample store producer/consumers

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java
Fix for issue reported in [711](https://github.com/linkedin/cruise-control/issues/711).
=> Add public default constructor for LeaderReplicaDistributionGoal.

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorState.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValues.java, cruise-control-core/src/test/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValuesTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/716.
* Also eliminates the repetitive sanity check for window range reset validity.
=> Prevent redundant updates to the window generation during the sampling and loading processes

kafka-cruise-control-stop.sh
This pull request addresses the issue #579.
Note: this script assumes that the only running java process is the cruise-control.
This is an example log output that I got from testing the command:
https://gist.github.com/emilyki/1dbbf380646c2079400faeb2c084f2fb
=> Add kafka-cruise-control-stop.sh.

build.gradle, config/log4j.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaAnomaly.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/AbstractCruiseControlResponse.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlResponse.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletEndpointTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
Addresses issue #595.
The new log will be called kafkacruisecontrol-result.log. It's rolled daily.
=> Added log for old user tasks, executor action and self-healing action

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/772.
=> Let anomaly detector keep a counter of anomalies (1) fixed and (2) checked with delay.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/GetClusterModelInRangeRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/PartitionLoadState.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/759 by adding `avg_load` parameter to `partition_load` endpoint.
-- Note that to get the average over a given time frame (e.g. the past 7 days), users can set `start` and `end` parameters with the relevant timestamps, accordingly.
=> Add explicit parameter to force retrieval of avg utilization of partitions

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java
=> Fix the bug that user cannot retrieve the detailed response of in-execution task with UUID.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AnomalyNotifier.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/NoopNotifier.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
Adds `self healing enabled ratio metric` specified at issue https://github.com/linkedin/cruise-control/issues/723.
=> Add self healing enabled ratio metric under anomaly_detector substate of state response.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java
Currently, it is possible for the `_metricConsumer.partitionsFor` method to return `null`, which then is assigned to `remotePartitionInfo`.
With the current logic, it is possible to attempt to invoke the `isEmpty` method on `remotePartitionInfo` while it is `null`, generating a `java.lang.NullPointerException`.  
```
2019/06/28 17:07:30.611 ERROR [OffspringServletRuntime] [main] [kafka-cruise-control] [] BOOT_1000 Boot listener com.linkedin.kafka.licruisecontrol.LiKafkaCruiseControlBootListener failed
java.lang.NullPointerException: null
at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.refreshPartitionAssignment(CruiseControlMetricsReporterSampler.java:186) ~[cruise-control-2.0.50.jar:?]
at …
```
=> Handle NPE in refreshPartitionAssignment

cruise-control-client/cruisecontrolclient/client/CCParameter/__init__.py, cruise-control-client/setup.py
Previously, `__init__.py` in `CCParameter` lacked a statement to import `NonNegativeIntegerParameter`.
Unfortunately, this meant that the `CCParameter.ReviewIDParameter` references in the various `Endpoints` was a nonsense reference, resulting in something like the following stack trace  
```
from cruisecontrolclient.client.ExecutionContext import ExecutionContext
File "/Users/mgrubent/src/ccdo_trunk/build/ccdo/venv/lib/python3.7/site-packages/cruisecontrolclient/client/ExecutionContext.py", line 5, in <module>
import cruisecontrolclient.client.Endpoint as Endpoint
File "/Users/mgrubent/src/ccdo_trunk/build/ccdo/venv/lib/python3.7/site-packages/cruisecontrolclient/client/Endpoint.py", line 170, in <module>
class AddBrokerEndpoint(AbstractEndpoint):
File …
```
=> Fix missing reference to ReviewIDParameter

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifier.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/827.
=> Fix incorrect computation of enabledTimeMs causing inaccurate selfHealingEnabledRatio reporting

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/AggregatedMetricValues.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/AsyncKafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/UpdateTopicConfigurationRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Partition.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Replica.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ReplicaSortFunctionFactory.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TopicConfigurationParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForLeadershipTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForReplicaMoveTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ReplicationFactorChangeTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
Fix issue #713  and issue #722
=> Honor goals when increasing topic replication factor.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
=> Make cruise control fail fast for real execution if there is any ongoing partition reassignments.

cruise-control-client/setup.py, docs/wiki/Python Client/README.md
Functionally, this commit introduces the ability for direct command-line access to `cccli` through the use of the [`entry_points` keyword argument](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation).
This commit also updates the Python Client README to direct users to `pip` for acquiring the `cruise-control-client` package, rather than cloning into this repo directly.
Finally, this commit adds a `long_description`, so that the [PyPI project page](https://pypi.org/project/cruise-control-client/) can have a description.
=> Add project description and command-line entrypoint

cruise-control-client/cruisecontrolclient/__init__.py, cruise-control-client/setup.py
Currently, the markdown on the [PyPI site for `cruise-control-client`](https://pypi.org/project/cruise-control-client/) renders in an unintended manner.
Accordingly, fix this rendering by specifying the description type.
Additionally remove needless comments from `__init__.py`.
Finally, remove reference to `cccli.py` in favor of consistent use of `cccli` command-line entry point, and patch version bump.
=> Fix broken PyPI markdown

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/AdminRequest.java
=> Remove the redundant dropRecentBrokersRequest field in response of admin endpoint.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolations.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SelfHealingNotifierTest.java
for issue #842 
If default.replication.throttle is not set in config file, null is the default value as defined in KafkaCruiseControlConfig(pr #748 ).
=> use config value for replicaThrottle in the fix method of Anomaly

cruise-control-core/src/test/java/com/linkedin/cruisecontrol/CruiseControlUnitTestUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregatorTest.java
Fix for issue #849
Another way to fix this issue is to directly make adjustment to RawMetrics(metrics reported by reporter) `BROKER_CPU_UTIL`, so that the newly generate samples have correct cpu utilization value for each partition/broker entity. 
But this approach breaks back-compatibility and there will be a transition period(where there is both new samples and old samples sitting in memory and get aggregated together) that the CC is unable to generate accurate workload profile for the cluster.
=> Fix wrong cpu metric value magnitude in cluster model.

cruise-control-client/cruisecontrolclient/client/Endpoint.py, cruise-control-client/setup.py
Previously, the `TopicConfigurationEndpoint` identified itself with an alias `stop`.
Unfortunately, there already exists an alias `stop`, belonging to the `StopProposalExecutionEndpoint`.
Accordingly, the `TopicConfigurationEndpoint`'s use of `stop` shadows the `StopProposalExecutionEndpoint`'s use of `stop`, such that  
```
cccli -a $somewhere stop
```
actually invokes the `TopicConfigurationEndpoint`.
This behavior is incorrect.
Accordingly, remove the `TopicConfigurationEndpoint`'s `stop` alias.
=> Un-shadow the stop endpoint

config/capacityCores.json, config/cruisecontrol.properties, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityInfo.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolverTest.java, cruise-control/src/test/resources/testCapacityConfigCores.json
Addresses the issue https://github.com/linkedin/cruise-control/issues/860.
=> Add support for BrokerCapacityInfo to keep number of CPU cores.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java
Current `GET` calls return the `access-control-allow-credentials` header but `OPTIONS` does not which causes some browsers not to make the `GET` call
=> fix missing CORS header in OPTIONS call

cruise-control-client/cruisecontrolclient/client/CCParameter/BooleanParameter.py, cruise-control-client/cruisecontrolclient/client/CCParameter/SetOfChoicesParameter.py, cruise-control-client/cruisecontrolclient/client/Endpoint.py, cruise-control-client/cruisecontrolclient/client/Query.py, cruise-control-client/cruisecontrolclient/client/Responder.py, cruise-control-client/cruisecontrolclient/client/cccli.py, cruise-control-client/setup.py, docs/wiki/Python Client/cruise-control-client-Usage-in-Python-Applications.md
Currently, there is no support for `cruise-control-client` passing a data payload to `cruise-control`.  
Accomplishing this at present would require some deep subclassing of the existing `Responder` classes.
Conceivably (e.g. as an outcome of #875), `cruise-control` will accept data payloads in the future.
This PR seeks to allow for `cruise-control-client` to easily pass arbitrary data payloads to `cruise-control`, by adhering more-closely to how `requests` creates and sends HTTP requests.
In short:  
```python
endpoint = get_endpoint(args=args, execution_context=e)
cc_socket_address = args.socket_address
data = {'a': 1}
json_responder = CruiseControlResponder()
response = json_responder.retrieve_response_from_Endpoint(cc_socket_address, endpoint, json=data)
```
This PR:  
1. Introduces a …
=> Allow easier passing of data payload

config/cruisecontrol.properties
added config example for the newly added config in PR (https://github.com/linkedin/cruise-control/pull/883)
Changes to be committed:
modified:   config/cruisecontrol.properties
=> added config example for logdir response timeout

cruise-control-client/cruisecontrolclient/client/CCParameter/RegularExpressionParameter.py
Small tweak which switches from using re.Pattern as the expected type of re.compile (which is Python 3.7 only) to using typing.Pattern. 
This makes the CLI runnable using Python 3.6 which many LTS Linux distros are still running.
=> Make CLI compatible with Python 3.6

cruise-control-client/cruisecontrolclient/client/cccli.py, cruise-control-client/setup.py
Currently, `get_endpoint` unintentionally mutates one of its passed arguments, `args`, by deleting some properties of this Object.
In `cccli.py` currently, this has no effect, as no method subsequent to `get_endpoint` relies on an un-mutated copy of `args`.
That said, it's bad style, and creates a pitfall in case `cccli.py` (or other user code) uses the buggy `get_endpoint` implementation.
`get_endpoint` now shallow copies the argument it expects to mutate, then mutates the shallow copy.
=> Fix failure-to-copy-Object bug

cruise-control-client/cruisecontrolclient/client/Display.py, cruise-control-client/cruisecontrolclient/client/Responder.py, cruise-control-client/cruisecontrolclient/client/cccli.py, cruise-control-client/setup.py
Mostly fixes #898 
Also fixes #873 
* Minor version bump, since `cccli.py` no longer includes `json=true` parameter by default
* Deprecate every function in `Display.py`, since these functions duplicate the human-readable text functionality of `cruise-control` itself
* Add support in `Display.display_response` for displaying non-JSON responses
* Remove `CruiseControlResponder.send` method override, which caused a correctness error (specifically, that `CruiseControlResponder` would not maintain the session in subsequent requests)
* Add response-finality checks for whether response code is `202`, and which `Cruise-Control-Version` string is returned in the header, in addition to whether the response is JSON (and has a `progress` key) or text
=> Add support for text responses

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
I see that the validation requires us to have a larger sampling rate than interval, yet the comments say the opposite
This was probably a typo in the original PR:
https://github.com/linkedin/cruise-control/pull/730/files#diff-23050e53166d8fdaaca2ce7299086068R1399
cc @efeg @kidkun
=> Better clarify sampling/reporting frequency validations

cruise-control-client/cruisecontrolclient/client/Display.py, cruise-control-client/cruisecontrolclient/client/Responder.py, cruise-control-client/cruisecontrolclient/client/cccli.py, cruise-control-client/setup.py
Fixes #927.
This proposed change also removes default use of the deprecated function `display_response`, in favor of a straight `print` statement.  
Non-final responses will be printed to `stderr`, while final responses are returned to the caller.
=> Ensure that json module is used

build.gradle
=> Remove extra test.dependsOn from subprojects

cruise-control-client/cruisecontrolclient/client/Responder.py
```
integer_semver = lambda x: [int(elem) for elem in x.split('.')]
ValueError: invalid literal for int() with base 10: '0-SNAPSHOT'
```
ValueError occurs because logic not stripping out non-numeric characters
=> Fixing Snapshot coming into the version #

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/holder/BrokerLoad.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/951.
=> Ensure that brokers for failed partition metric samples are identified when possible.

cruise-control-client/cruisecontrolclient/client/CCParameter/CommaSeparatedParameter.py, cruise-control-client/cruisecontrolclient/client/Endpoint.py, cruise-control-client/setup.py
This should make progress on #897 by adding `drop_recently_demoted_brokers` and `drop_recently_removed_brokers` to the `admin` Endpoint.
=> Drop brokers from list

build.gradle, gradle/wrapper/gradle-wrapper.properties
Addresses the issue https://github.com/linkedin/cruise-control/issues/1008.
=> Bump up slf4j-api, jetty-servlet, jetty-server, easymock, and gradle.

cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RequestParameterTest.java, cruise-control/src/yaml/base.yaml, cruise-control/src/yaml/endpoints/load.yaml
Add OpenAPI Load endpoint for only cluster load as partition load is accessed via a different path and capacity is not yet merged.
=> Add OpenAPI yaml spec for Load endpoint

docs/wiki/User Guide/REST-APIs.md
```
cruise-control-rest# curl -X POST localhost:9095/kafkacruisecontrol/admin?concurrent_intra_partition_movements=12
Unrecognized endpoint parameters in ADMIN POST request: [concurrent_intra_partition_movements]
cruise-control-rest# curl -X POST localhost:9095/kafkacruisecontrol/admin?concurrent_intra_broker_partition_movements=12
{
ongoingConcurrencyChangeRequest: Intra-broker partition movement concurrency is set to 12
}
```
Addresses the issue of parameter name incorrect
https://github.com/linkedin/cruise-control/blob/5ed774eb5c64f6e57a6a001c1306c520170416c5/cruise-control/src/yaml/endpoints/admin.yaml#L39
=> Correct name for API parameter

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityInfo.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/exception/BrokerCapacityResolutionException.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/exception/BrokerCapacityResolvingException.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/LoadRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/ProposalsRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolverTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/RandomCluster.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsProcessorTest.java, cruise-control/src/test/resources/DefaultCapacityConfig.json
Addresses the issue #1107 .
The main change in this PR to evolve [BrokerCapacityConfigResolver#capacityForBroker](https://github.com/linkedin/cruise-control/blob/c84af32fcc96d1c4d026e8e4dd5aac54bb8ace6f/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigResolver.java#L38) method signature by adding a new argument `allowCapacityEstimation `. 
Doing so have multiple advantages. 
1. Now `BrokerCapacityConfigResolver` is aware that estimation is allowed or not, so it no longer makes blindly assumption.
2. Now in cluster model generation process, if `BrokerCapacityConfigResolver`  returns failing response, we can fail early; if `BrokerCapacityConfigResolver`  returns success response, we are certain that the generated cluster model satisfies estimation …
=> Evolve BrokerCapacityConfigResolver interface to be aware whether capacity estimation is allowed or not in broker capacity resolution.

cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/SslConnectionIntegrationTest.java
Fixes the test by adding the webserver.ssl.enable config and checks if the used protocol is HTTPS.
=> Fix HTTP test by checking the actual protocol

build.gradle, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/BasicSecurityProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/DefaultRoleSecurityProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/UserStoreAuthorizationService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtAuthenticator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtLoginService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtSecurityProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtUserIdentity.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtUserPrincipal.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/CruiseControlIntegrationTestHarness.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/SecurityAndSslConfigTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/AuthenticationIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/BasicAuthenticationIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/SslConnectionIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtAuthenticatorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtLoginServiceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtSecurityProviderIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/TokenGenerator.java, cruise-control/src/test/resources/jwt-auth.credentials, docs/wiki/User Guide/Security.md
Addresses the issue #1065.
It defines a JwtAuthenticator and a JwtLoginService and bundles them together in a JwtSecurityProvider class. The authenticator can interpret tokens provided in the Authorization header using the Bearer scheme or provided in a cookie. The tokens are encrypted and a certification has to be present in Cruise Control to be able to verify the tokens.
Changed config names:
basic.auth.credentials.file -> webserver.auth.credentials.file: the motivation behind this is to change it into a more generic password file configuration.
New configs:
- jwt.authentication.provider.url
- jwt.cookie.name
- jwt.auth.certificate.location
- jwt.expected.audiences
Testing:
- unit tests for verifying JwtAuthenticator and JwtLoginService
- integration test to verify the whole end-to-end …
=> JWT Authentication

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/DefaultOptimizationOptionsGenerator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptionsGenerator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/AnalyzerConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java
Addresses the issue #1151 .
As a follow up of PR #1150, in order to let `GoalViolationDetector` and `GoalOptimizer` use customized `OptimizationOptions` without extending these two class,  this PR add a new pluggable component, `OptimizationOptionsGenerator` to handle the related logic.
=> Refactor out the optimization options generation logic of GoalViolationDetector and GoalOptimizer into a pluggable component.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlApp.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java
Changing them to `Password` will hide the actual values at logging.
=> Change webserver ssl keystore and key password to password type

cruise-control/src/yaml/endpoints/demoteBroker.yaml, cruise-control/src/yaml/endpoints/fixOfflineReplicas.yaml, cruise-control/src/yaml/endpoints/load.yaml, cruise-control/src/yaml/endpoints/partitionLoad.yaml, cruise-control/src/yaml/endpoints/proposals.yaml, cruise-control/src/yaml/endpoints/rebalance.yaml, cruise-control/src/yaml/endpoints/removeBroker.yaml, cruise-control/src/yaml/endpoints/reviewBoard.yaml
Fixes a couple of typos in the OAS3 API yaml descriptor files, such as typos, type errors (set and map definitions) so that the yaml will be compilable with the openapi-generator tool too.
=> Fix typos and invalid types in OAS3 yaml

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, docs/wiki/User Guide/REST-APIs.md
Addresses issue #1187, where the user tasks endpoint returns an error if a task `CompletedWithError` and `fetch_complete_task=true` is in the request. This prevents the user from learning the state of these tasks.
This changes the `getJSonStructure` method to not throw an error for `CompletedWithError` tasks when `fetch_complete_task=true` and instead just return `"CompletedWithError"` in the `originalResponse` field.
=> Fix #1187: User tasks endpoint returns error for CompletedWithError tasks when fetch_complete_task=true

cruise-control-client/cruisecontrolclient/client/CCParameter/BooleanParameter.py, cruise-control-client/cruisecontrolclient/client/Endpoint.py, cruise-control-client/setup.py
Fixes #1189.
Note that, under this implementation, the `force_stop` parameter will always be supplied to `cruise-control` when `cccli` executes the `stop_proposal_execution` command.  
If `--force-stop` is not provided, the value of this parameter will be `False`.  
If `--force-stop` is provided, the value of this parameter will be `True`.
Force stop is a potentially disruptive action, so there is a sensible default here, which is `False`.
Older versions of `cruise-control` which do not understand the `force_stop` parameter will return an exception when using `1.1.*` of `cccli`.
`cccli` compatibility with these older versions of `cruise-control` can be achieved in one of two ways:  
1. Remaining on `ccclient` `1.0.*`.  There are no plans to back-port `force_stop` support to `1.0.*`.  
2. …
=> [ccclient-1.1.0] Add force_stop parameter

build.gradle
Addresses the issue #1193
Upgrading to swagger-parser-v3 removes a good chunk of dependencies, and decreases the footprint of the project.
=> Use swagger-parser-v3 to eliminate compat dependencies

.circleci/config.yml, build.gradle, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedBroker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorAdminUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizerTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/CaseInsensitiveGoalConfigTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1167 by adopting the admin client-based replica reassignment API for `Kafka 2.4+` on development branch `migrate_to_kafka_2_4`.
-- This patch does not address https://github.com/linkedin/cruise-control/issues/1195.
=> Add AdminClient-based replica reassignment.

cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RandomClusterTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1200.
-- e.g. local testing time for `RandomClusterExpDistNewBrokerTest` goes from `10m 48sec` to `3m`.
=> Eliminate repetitive random cluster tests.

.circleci/config.yml, build.gradle, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BrokerStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/SingleBrokerStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/SingleHostStats.java, cruise-control/src/yaml/responses/brokerStats.yaml
Addresses the issue #1192.
* This patch also picks up `CircleCI` config updates, jacoco plugin, and relevant executor refactoring merged in https://github.com/linkedin/cruise-control/pull/1196.
* The plaintext output format has been verified on local deployment.
=> Add rack information to load response.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
=> Fix NPE if task execution takes longer than executionProgressCheckIntervalMs().

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/common/LongGenerationed.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/AggregationOptions.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregationResult.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregator.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleCompleteness.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/RawMetricValues.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/ValuesAndExtrapolations.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/aggregator/KafkaPartitionMetricSampleAggregator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/SessionManager.java
Compiling cruise-control with java-11 rendered errors in javadocs target due to invalid (in java-11) `tt` html tag.
=> Fixed java11 javadocs errors

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ReplicationFactorChangeTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtilsTest.java
Addresses the issue https://github.com/linkedin/cruise-control/issues/1221.
=> Ensure that requests to update replication factor cannot cause a deadlock.

.circleci/config.yml, build.gradle, checkstyle/checkstyle.xml, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaClientsIntegrationTestHarness.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailures.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricSamplerPartitionAssignor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/SecurityUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyAuthorizationService.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtAuthenticatorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/jwt/JwtLoginServiceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoUserStoreAuthorizationServiceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginServiceTest.java
use java-11 to compile:
- migrated from findbugs to spotbugs (findbugs won't work with java 11). This required separation of spotBugs gradle task in a separate run in CircleCI to avoid out of memory issues
- fixed checkstyle config files discovery
- fixed on prio 1 bug `VO_VOLATILE_INCREMENT` reported in AnomalyDetector.java
- upgraded org.eclipse.jetty.security and fixed tests to provide a non-null Credential
=> Compile using java 11

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/UserTaskState.java
This PR fixes the response for `completedWithError` tasks on the `user_tasks` endpoint for requests where `json=false`. The previous fix (#1188) only applied to `json=true` requests.
Signed-off-by: Thomas Cooper <tom.n.cooper@gmail.com>
Addresses the issue #1187
=> Additional fixes for user tasks endpoint

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
=> Fix java.lang.NoClassDefFoundError: org/apache/kafka/clients/admin/Admin in Cruise Control Metrics Reporter

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/LoadRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ClusterLoadParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/yaml/endpoints/load.yaml, docs/wiki/User Guide/REST-APIs.md
This PR resolves #1191.
-- 
Example plaintext response, where values are defined for entries in `<...>`:
```
HOST         BROKER      RACK         DISK_CAP(MB)            DISK(MB)/_(%)_            CORE_NUM         CPU(%)          NW_IN_CAP(KB/s)       LEADER_NW_IN(KB/s)     FOLLOWER_NW_IN(KB/s)         NW_OUT_CAP(KB/s)        NW_OUT(KB/s)       PNW_OUT(KB/s)    LEADERS/REPLICAS
<hostname-here>,          <id>,     <id>,        <diskCap-mb>,              0.000/00.00,            <cores>,         0.000,              <capacity>,                   0.000,                   0.000,              <capacity>,              0.000,              0.000,             0/0
<hostname-here>,          <id>,     <id>,        <diskCap-mb>,              0.000/00.00,            <cores>,         0.000, …
```
=> Add support to retrieve capacity only via load endpoint.

docs/wiki/User Guide/REST-APIs.md
The intra-broker concurrent partition movement parameter name is wrong in the REST API wiki. This PR fixes that and adds the expected units for the replication throttle parameter.
=> Fix wrong concurrent intra broker movement parameter name 

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/EnvConfigProvider.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/EnvConfigProviderTest.java, cruise-control/src/test/resources/envConfigProviderTest.properties, docs/wiki/User Guide/Configurations.md
This commit enables parsing config values from environment variables.
This is particularly useful if passwords can't be hardcoded in the config
files but instead passed to Cruise Control via an environment variable.
For instance if there is a MY_PASSWORD=test123 then defining the following
config in cruisecontrol.properties will be resolved on startup to the
actual password.
Config file on the disk: config.name=${env:MY_ENV_VAR}
Resolved runtime config: config.name=test123
This fixes #1197
=> Environment variable resolution in configs

.circleci/config.yml
=> Rollback to known good JDK 8 due to memory leak introduced in JDK 11

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/SampleLoadingTask.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java, cruise-control/src/yaml/responses/executorState.yaml, docs/wiki/User Guide/REST-APIs.md
This PR resolves #969 and #1259.
* Removes pause sampling after loading regardless of ongoing execution
* Ensures that executor state is consistent within ProposalExecutionRunnable in preparation for #909.
* Adds `INITIALIZING_PROPOSAL_EXECUTION` executor state for #909.
* Extracts execution util functions to a utility class.
=> Prevent Cruise Control from mistakenly believe that there is an ongoing execution

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterBrokerState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java, cruise-control/src/yaml/responses/kafkaClusterState.yaml
This PR resolves #1247 and #1092.
Expected response format has been verified via a deployment:
1. Plaintext response --
```
Summary: The cluster has 9 brokers, 2331 replicas, 777 leaders, and 42 topics with avg replication factor: 3.00. [Leaders/Replicas per broker] avg: 86.33/259.00 max: 146/320 std: 36.51/93.82
<The existing kafka_cluster_state plaintext response>
```
2. JSON response --
Adds the `Summary` under `KafkaBrokerState`.
```
"Summary":{"StdLeadersPerBroker":36.50875085358151,"Leaders":777,"MaxLeadersPerBroker":146,"Topics":42,"MaxReplicasPerBroker":320,"StdReplicasPerBroker":93.82015893304713,"Brokers":9,"AvgReplicationFactor":3.0,"AvgLeadersPerBroker":86.33333333333333,"Replicas":2331,"AvgReplicasPerBroker":259.0}
```
Note: Changes of constants and selected response …
=> Add summary response to kafka_cluster_state

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedTopicsTest.java, docs/wiki/User Guide/Pluggable-Components.md
=> LeaderReplicaDistributionGoal should honor excludedTopics during leadership movement.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/AddBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/DemoteBrokerRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/FixOfflineReplicasRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/GoalBasedOperationRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/ProposalsRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RebalanceRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/yaml/responses/executorState.yaml, docs/wiki/User Guide/REST-APIs.md
This PR resolves #909.
* Adds `GENERATING_PROPOSALS_FOR_EXECUTION` executor substate to reflect the state after receiving a non-dryrun execution request and before `INITIALIZING_PROPOSAL_EXECUTION`.
=> Let executor substate show information on process before starting an execution

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
=> Prevent concurrent execution request from corrupting ongoing execution state.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, docs/wiki/Python Client/cccli-Command-Line-Usage.md
This PR resolves #1195.
* Changes in this PR are relevant to `migrate_to_kafka_2_4` and `migrate_to_kafka_2_5` branches.
=> Support stop ongoing executions with rollback

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTask.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java, cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskManagerTest.java, gradle.properties
This PR resolves #1309 and allows the Cruise Control Metrics reporter to work with Kafka 2.6 brokers.
This PR also refactors the `ExecutionTask.State` enum into its own separate class. This is needed as switching to the Kafka 2.6 libraries causes the gradle scala compiler to throw cyclical reference errors for this class.
=> Add support for Kafka 2.6 brokers

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java
This PR resolves #1296.
-- also note that `assert` statement is removed as (1) it is typically not enabled anyway (i.e. unless users explicitly use the `-ea` switch, it is disabled) and (2) this makes metrics reporter more defensive against Yammer metrics with an unexpected scope.
=> Skip parsing scopes that have keys without a matching value.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/LoadRunnable.java
This PR resolves #1353 
Notes for reviewers:
The implementation is based on the assumption that if a `Broker` has multiple `Disk`s, it must be using JBOD. Please correct me if this assumption is incorrect. Thanks!
=> Check whether a cluster is using JBOD when populate_disk_info is true

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/AbstractMetricSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcher.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricSampler.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricSamplerOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/NoopSampler.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
This PR extracts the code from `CruiseControlMetricsReporterSampler` that initiates the MetricProcessor and uses it to convert `CruiseControlMetric` objects into `Sample` objects into an `AbstractMetricSampler` class. This code is reusable, and can be utilized by other implementations of `MetricSampler`.
We also encapsulate the options passed to `getSamples` method of `MetricSampler` into an `MetricSamplerOptions` class, so that it is extensible in the future by adding more fields to it, without breaking API compatibility. We are deprecating the older signature of `getSamples` that uses individual arguments.
=> Make MetricSampler more extensible.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/LinearRegressionModelParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/CruiseControlState.java
This PR resolves #1356.
The current way of handling the `SingularMatrixException` is very non-aggressive. Another more aggressive way to handle it could be throwing 5XX internal server error since it's technically the logic on the CC server cannot figure out the linear regression model.
=> Catch and handle exception thrown while linear regression model state gets computed

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/BootstrapParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ClusterLoadParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/PartitionLoadParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/TrainParameters.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtilsTest.java
This PR resolves #1355.
Notes for code reviewer:
This PR adds the below methods `ParameterUtils.endMsOrDefault` and `ParameterUtils.startMsOrDefault`. The reason is that it should be up to the caller to decide the default values for start time and end time. Depending on which `AbstractParameters` class parses the request, they might have different default values for start time and/or end time.
The original `startMs` and `endMs` returns null if no start/end time is set in the request.
=> Add check to validate that time range start time is smaller than end time

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MaintenanceEventTopicReader.java
=> Prevent MaintenanceEventTopicReader from prematurely closing the adminClient.

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
Cruise Control (CC) can fail to collect sufficient metrics from low traffic Kafka clusters for an extended period of time, which would make CC unable to handle model-based (e.g. get cluster `load`) or goal-based (`rebalance` the cluster using the default goals) operations – e.g.
```
Error processing GET request '/partition_load' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1603951915056] for aggregation options (minValidEntityRatio=0.98, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=55498, granularity=ENTITY)'.
```
We have already exposed the relevant config to fix similar observed issues in …
=> Enable Cruise Control to collect metrics from low traffic clusters by default

config/cruisecontrol.properties, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractRackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionAbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUnitTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForReplicaMoveTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/IntraBrokerRebalanceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java
* Ensure that `RackAwareDistributionGoal`, `TopicReplicaDistributionGoal`, `ReplicaDistributionGoal`, `LeaderReplicaDistributionGoal` do not include brokers excluded for replica moves while computing balance constraints.
* Fix incorrect `numOfflineTopicReplicasInB1` within `rebalanceByMovingReplicasIn` of `TopicReplicaDistributionGoal`.
* Update the following dead configs, which are not supported after https://github.com/linkedin/cruise-control/pull/985 in `cruisecontrol.properties`:
```
broker.failure.exclude.recently.demoted.brokers=true
broker.failure.exclude.recently.removed.brokers=true
goal.violation.exclude.recently.demoted.brokers=true
goal.violation.exclude.recently.removed.brokers=true
```
This PR resolves #1382.
--
Selected evaluations on a cluster with 10 brokers with 3 …
=> Ensure that topology distribution goals compute balance constraints properly

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/Resource.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Broker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Load.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/ExcludedBrokersForReplicaMoveTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/DeterministicCluster.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/common/TestConstants.java
* Ensure that `CpuUsageDistributionGoal`, `DiskUsageDistributionGoal`, `NetworkInboundUsageDistributionGoal`, `NetworkOutboundUsageDistributionGoal`, `DiskCapacityGoal`, `NetworkInboundCapacityGoal`, `NetworkOutboundCapacityGoal`, `CpuCapacityGoal`, `LeaderBytesInDistributionGoal` do not include brokers excluded for replica moves while computing balance constraints (`PotentialNwOutGoal` does not need further changes).
This PR resolves #1384.
-- Selected Evaluation --
Selected evaluations on a cluster with 10 brokers with 3 brokers permanently marked as excluded -- i.e. preferred controllers of [LinkedIn Kafka](https://github.com/linkedin/kafka) -- please note standard deviations (lower is better).
Standard deviation **before** and **after**:
- CpuUsageDistributionGoal: 42.917 -> 1.919
- …
=> Ensure that resource distribution goals compute balance constraints properly

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetails.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomaly.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetailsTest.java, docs/wiki/User Guide/Pluggable-Components.md
* Drop redundant override for `KafkaMetricAnomaly#optimizationResult`
This PR resolves #1417.
=> Add missing population of anomaly details for maintenance events

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
=> Handle missing listeners config in CruiseControlMetricsReporter

README.md
Add information about `capacity.config.file` to README.md. 
Cruise Control server can start with the default file, but the capacity information may not be correct. This is because the default resolver of Cruise Control uses `capacity.config.file` as the source of truth to determine the capacity of brokers. 
Thus, `capacity.config.file` should be specified by the user. Without doing so, the default file may not show the correct capacity of brokers, which might fail the proposal process in further.
This PR resolves #1052 #325.
=> Add information about `capacity.config.file` to README.md

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/ExecutorConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtilsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
=> Remove the future-level timeout for the processAlterPartitionReassignmentsResult method

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/MetricAnomalyFinder.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/MetricAnomalyType.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinder.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/MetricAnomalyDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/NoopMetricAnomalyFinder.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/KafkaMetricAnomalyFinderTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinderTest.java, docs/wiki/User Guide/Sensors.md
This PR resolves #1210.
1. Adds the following sensors:
| DESCRIPTION                                                                                               | MBEAN NAME                                        				            |
|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
| The number of brokers that are metric anomaly suspects, pending more evidence to conclude either way      | kafka.cruisecontrol:name=AnomalyDetector.num-suspect-metric-anomalies         |
| The number of brokers that have recently been identified with a metric anomaly                            | kafka.cruisecontrol:name=AnomalyDetector.num-recent-metric-anomalies …
=> Add sensors to report the number of slow brokers

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizerResult.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java
This PR resolves #1475.
* It also removes an extra `dot` from provision response.
=> Fix miscalculated recommendation for the number of racks to drop for clusters over-provisioned wrt rack count.

build.gradle, config/log4j.properties, cruise-control-core/src/test/resources/log4j.properties, cruise-control-metrics-reporter/src/test/resources/log4j.properties, cruise-control/src/test/resources/log4j.properties, kafka-cruise-control-start.sh
This PR resolves #1473.
* Verified via local deployment that the current logs in use (i.e. `kafkacruisecontrol.log` and `kafkacruisecontrol-operation.log`) are populated as expected.
* The `kafka-cruise-control-start.sh` starts Cruise Control without errors or warning such as the following:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/some-path-here/cruise-control/cruise-control/build/dependant-libs/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/some-path-here/cruise-control/cruise-control/build/dependant-libs/log4j-slf4j-impl-2.14.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of …
```
=> Make SLF4J API use Log4j2 as the implementation

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/KafkaNetworkClientProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/MetadataClient.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/NetworkClientProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java, gradle.properties
This PR adds support for kafka version 2.7.
It adds support for the configurable socket connection timeout in NetworkClient introduced in [KIP-601](https://cwiki.apache.org/confluence/display/KAFKA/KIP-601%3A+Configurable+socket+connection+timeout+in+NetworkClient)
=> Add support for kafka version 2.7

README.md, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitorTest.java
This PR resolves #1479.
* Makes other minor updates in readme (e.g. Kafka scale at LinkedIn)
* Cherrypicks `LoadMonitorTest` changes from https://github.com/linkedin/cruise-control/pull/1471 for consistency across branches
=> Add documentation regarding Kafka 2.7 support.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, docs/wiki/User Guide/Sensors.md
This PR resolves #1365.
Relevant Notes
* An _eligible_ rack is an alive rack that is allowed replica moves. A rack is alive and allowed replica moves as long as it has at least one alive host, which is not excluded for replica moves. A host is alive and allowed replica moves if it has at least one alive broker, which is not excluded for replica moves.
* An ongoing execution may modify the replication factor of partitions; hence, the detector avoids reporting potential false positives.
* The sensor is configured to be refreshed once in every `goal.violation.detection.interval.ms`; hence, it could be temporarily stale at most as long as this interval if during this time
(1) new topics would be created with a replication factor > number of eligible racks in a cluster for the first time, or …
=> Add a sensor to indicate if the cluster has partitions with RF > the number of eligible racks

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java
Before this commit, we'd print an error message that looks something like `java.lang.IllegalStateException: Missing disk information for disk /mnt/disk1/kafka on broker ClusterModel[brokerCount=15,partitionCount=0,aliveBrokerCount=15]`. This seems a bit odd, since `ClusterModel` is not a broker.
After this commit, we'll instead print something more like `java.lang.IllegalStateException: Missing disk information for disk /mnt/disk1/kafka on broker Broker[id=1052,rack=kafka1052.us-e.ec2.liftoff.io,state=ALIVE,replicaCount=0,logdirs=[/mnt/disk0, /mnt/disk1, /mnt/disk10, /mnt/disk11, /mnt/disk12, /mnt/disk13, /mnt/disk14, /mnt/disk15, /mnt/disk16, /mnt/disk17, /mnt/disk18, /mnt/disk19, /mnt/disk2, /mnt/disk20, /mnt/disk21, /mnt/disk22, /mnt/disk23, /mnt/disk3, /mnt/disk4, /mnt/disk5, …
=> Fix error message for missing disk information

kafka-cruise-control-stop.sh
This PR resolves [1531](https://github.com/linkedin/cruise-control/issues/1531).
For cruise control, we should use the main class to filter the process id in the stop step, so as to avoid accidentally killing other processes that rely on cruise control.
=> Consolidate the stop script to avoid stopping the kafka service

build.gradle, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/SamplingUtils.java, gradle.properties
This PR resolves #1539.
* Explicitly specify the version of Netty dependencies instead of relying on the version set by ZooKeeper, which contains several CVEs. I also verified that the dependency tree now has the latest versions for Netty dependencies after this PR.
* Avoid bumping up `spotbugs` `toolVersion` to `4.2.3` due to false positives regarding `DMI_RANDOM_USED_ONLY_ONCE` (see reported issue: https://github.com/spotbugs/spotbugs/issues/1504#issuecomment-821820920)
* Share a single Random object across the main project.
=> Bump up stale dependencies

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskTracker.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricFetcherManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, docs/wiki/User Guide/Sensors.md
This PR resolves #1562 and #1563.
* Also move the `Cruise Control sensor types -- i.e. the first element of the metric name` to a utility class.
=> Add timers to track goal violation detection and fix generation for self-healing

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, docs/wiki/User Guide/Configurations.md
This PR resolves #1548
I think that this was what was wanted but not exactly sure
=> Remove unused skip.sample.store.topic.rack.awareness.check config

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlApp.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java
This PR resolves #1582.
CruiseControl webserver uses Jetty and relies on the Jetty SslContextFactory. In some environments, it is beneficial to configure TLS protocol/cipher whitelist/blacklist that the server should enable.
Four new configuration properties are introduced:
- webserver.ssl.exclude.ciphers
- webserver.ssl.include.ciphers
- webserver.ssl.exclude.protocols
- webserver.ssl.include.protocols
These are used to configure the corresponding properties in the Jetty SslContextFactory.
=> Ability to configure TLS protocols and ciphers via configuration (#1582)

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModelStats.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Host.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Rack.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicas.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/SortedReplicasHelper.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/OptimizationVerifier.java
This PR resolves #1580.
The selected inefficiencies addressed in this PR have been identified based on CPU profiling during optimization of goals. This patch does not cover _all_ potential inefficient code paths, but only addresses key inefficiencies that stand out in profiling results.
As a result of these improvements, clean build time of Cruise Control with all unit tests and static analysis dropped from
* [on Local box] `~16 minutes` to `~14.5 minutes` -- i.e. local CC build is `9.4%` faster
In particular, local run of the `RandomClusterExpDistNewBrokerTest` (i.e. one of the most expensive CC test that performs multiple goal optimizations with different parameters) has dropped from 
* [on Local box] `3minutes 50s` to `3minutes 10s`, which means `~17.4%` improvement. _Note: Performance …
=> Identify and fix inefficient code paths in goal optimization

CONTRIBUTING.md, build.gradle, checkstyle/checkstyle-pre-commit
I often forget to run CheckStyle before pushing a commit, which then fails the CI build. Therefore I added a pre-commit hook to run checkstyle (via the gradle checkstyle plugin). This is obviously optional, it does increase the time to do a commit, but it reduces the wasted effort of running CI on something that has style issues.
=> Add (optional) checkstyle pre-commit hook script

README.md, build.gradle
This PR resolves #1600.
**Notes.** It also drops
1. the deprecated `classifier` and adds  `archiveClassifier.set(xxx)` instead, and
2. `jcenter()` dependency, which shows the warning -- _Builds will no longer be able to resolve artifacts from JCenter after February 1st, 2022_
=> Add Java version compatibility to use

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/BootstrapRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/BootstrapParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/BootstrapResult.java, cruise-control/src/yaml/endpoints/bootstrap.yaml
This PR resolves #1579.
With this PR, bootstrap endpoint will be disabled unless the request explicitly sets the `developer_mode` parameter to `true`.
=> Disable bootstrap endpoint in non-developer_mode

cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
=> Cleanup deprecated/unused kafkaZkClient-based ExecutorUtils functions

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/PartitionSizeAnomalyFinder.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicPartitionSizeAnomaly.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/AlertaSelfHealingNotifier.java
This PR resolves #1528.
Note: This PR sets the default self healing partition size threshold to `1Tib`.
=> Fix inconsistent use of disk unit in partition size anomalies

build.gradle, gradle.properties
This PR adds the scala version to the `gradle.properties` file and calculates the scala binary version so the correct kafka dependency can be requested.
Will this be ported to the migrate branches or should I open separate PRs for those?
=> Parameterise the scala version in the gradle build

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/TopicPartitionSizeAnomaly.java
This PR resolves #1528.
- Looks like this change was missed in the [earlier PR](https://github.com/linkedin/cruise-control/pull/1609).
- As a side note, I also verified that after the [earlier PR](https://github.com/linkedin/cruise-control/pull/1609), the topic size anomaly detection works as expected.
=> Fix the unit in TopicPartitionSizeAnomaly#toString() to MB from bytes.

cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunnerTest.java
This PR resolves #1640.
* Also drop unused `KafkaZkClient`-based functions from the `master` branch, which were already removed from other active branches.
=> Drop the use of AdminZkClient for topic creation

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyAuthorizationService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProvider.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/SpnegoIntegrationTestHarness.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginServiceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderSpnegoFallbackIntegrationTest.java
In some scenarios we would also like to allow service users to be
authenticated and perform a Cruise Control action that they're
authorized to do. A nice option to enable this is to allow trusted
proxy to fall back to spnego.
That is when this functionality is enabled via the newly created
trusted.proxy.spnego.fallback.enabled option and no doAs user provided,
the TrustedProxySecurityProvider will authenticate and authorize the
service user.
This PR resolves #1617.
=> Allow trusted proxy to fall back to spnego

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/ProvisionRecommendation.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/CruiseControlParametersConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/CruiseControlRequestConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/NoopProvisioner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/Provisioner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ProvisionerState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ProvisionerUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/RightsizeOptions.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/CruiseControlEndPoint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/RightsizeRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RightsizeParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/RightsizeResult.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/ProvisionerStateTest.java, cruise-control/src/yaml/base.yaml, cruise-control/src/yaml/endpoints/rightsize.yaml, cruise-control/src/yaml/responses/rightsizeResult.yaml, docs/wiki/User Guide/REST-APIs.md
This PR resolves #1645.
Created a provisioner state object to track changes for rightsizing a cluster.
Added a test endpoint `Rightsize` to perform integration testing on the provisioner.
=> Setup ProvisionerState for rightsizing clusters

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/common/TopicMinIsrCache.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaAdminTopicConfigProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RunnableUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/StopProposalRequest.java, cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtilsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR resolves #1643.
* Adopt AdminClient-based leadership reassignment to replace KafkaZkClient
* Drop ZK-based calls to check existence of ongoing leadership reassignments (i.e. via `/admin/preferred_replica_election`) as they are no longer relevant under AdminClient-based leadership election
* Make force-stop requests function as the same as regular stop requests -- i.e. deletion of PLE znode and a following controller bounce is no longer relevant.
-- 
In addition to unit tests, I verified the functionality on a test cluster by performing leadership reassignment via demotion and rebalance.
=> Move PLE / leadership movement requests from KafkaZkClient to AdminClient

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
=> Decrease the linger time of metrics reporter to avoid discarding metrics in low traffic clusters

build.gradle, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/config/EnvConfigProvider.java, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/config/EnvConfigProviderTest.java, cruise-control-metrics-reporter/src/test/resources/envConfigProviderTest.properties
This development enables parsing config values from environment variables. This is particularly useful if sensitive information can't be hardcoded in the config files but instead passed to Cruise Control via an environment variable.
Furthermore this change is optimise the dependencies by removing unused one and rearrange groups.
This PR resolves #1649.
=> Create ConfigProvider in Cruise-Control-Metrics-Reporter modul and optimise dependencies

cruise-control-client/setup.py
#1671 made some changes to `cruise-control-client`, but I neglected to bump its version in the PR.
So, patch-version-bump here.
=> Bump version for cruise-control-client changes

.circleci/config.yml
=> Migrate from the OpenJDK legacy image to the newest image

build.gradle
This change enables using the gradle install command to publish artifacts to local maven repository.
=> Add maven plugin to gradle

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
Add line to use reconnect.backoff.ms when specified, without this line it is not being applied to the Admin Client which can prevent connections to a busy cluster
This PR resolves #1694 .
=> Apply reconnect.backoff.ms configs to all contexts

build.gradle, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCKafkaIntegrationTestHarness.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/BrokerFailureIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlIntegrationTestUtils.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapacityViolationIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapcaityViolationIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java
In this change I would like to add three test cases. Each test cause a goal violation or anomaly detection on a healthy environment and wait until Cruise Control self healing fix the issue.
- **BrokerFailureIntegrationTest** removes a broker from the Kafka cluster and wait until all the partitions are fixed
- **ReplicaCapcaityViolationIntegrationTest** The brokers have more replicas than the allowed maximum replicas. After ReplicaCapacityGoal violated adding a new broker to the cluster should fix 
- **TopicAnomalyIntegrationTest** creates a test topic with less partition replica than the desired value configured by SELF_HEALING_TARGET_TOPIC_REPLICATION_FACTOR_CONFIG. After that it waits until the replica count not fixed. 
Also a new integrationTest task created in the build.gradle file to …
=> Add integration tests for Cruise Control self healing 

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
KafkaConfig.PortProp() -> "port"
This PR resolves #1740.
=> evaluate function that didn't implement in kafka version3

build.gradle
This PR updates log4j to 2.15
Fixes #1753
=> Upgrade log4j2 to 2.15 to fix CVE-2021-44228

build.gradle
This PR resolves #1753.
Previously we thought that https://github.com/linkedin/cruise-control/pull/1757 fixes this issue.
But looks like `log4j2` `2.15.0` is still vulnerable - we should use `2.16.0`
See: https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
=> Upgrade log4j2 to 2.16 to really fix CVE-2021-44228

.circleci/config.yml
This PR resolves #1736.
The extension to the current Circle CI setup allows to run the cruise-control tests for non-Intel architectures. As first step
`linux/s390x` platform is used. New platforms can be added to the existing matrix, once there is interest for it. The tests for non-Intel architecture are executed in parallel with the standard build/test job, so no extra time is used for the whole test pipeline.
The idea is to run docker container on standard Intel host via standard Circle CI setup in hardware emulation mode via docker `--platform` parameter and do the tests inside the container, similar to how it can be executed on real ARM, Power or Z hardware. To make sure which architecture is emulated inside the container - `uname -a` command is executed before the actual test.
The …
=> Run cruise-control tests for s390x architecture

build.gradle
Upgrade Log4j to 2.17.1 to address CVE-2021-45105 and [CVE-2021-44832](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832)
Vulnerability Details:
- https://logging.apache.org/log4j/2.x/security.html
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
Release Notes: 
- https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.0
- https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.1
=> Upgrade log4j to 2.17.1 to address CVE-2021-45105

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlApp.java
This PR resolves #1707
When `webserver.ssl.enable` is `true`, CC throws a NPE when `webserver.ssl.key.password` is not set in the CC configuration. [1]  Since Jetty automatically sets the KeyManagerPassword to the keystore password when the KeyManagerPassword is not explicitly set, [2] we don't always need to set it. We only need to set our client's KeyManagerPassword when the Kafka cluster we are connecting to sets it.  This PR just removes the requirement to set `webserver.ssl.key.password` when the Kafka cluster we are connecting to does not explicitly set the KeyManagerPassword.
[1] https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_4/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlApp.java#L107
[2] …
=> Allow webserver.ssl.key.password to rely on default value

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java, cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java
This reverts commit cf4585d799b3ada3027b72ba2deef3bf9af4a52f
This commit has caused the tests that are relevant to replication throttle to be flaky (see [CI#4984](https://app.circleci.com/pipelines/github/linkedin/cruise-control/1689/workflows/27696a50-fe52-4231-8edd-ac821716e16f/jobs/4984), [CI#4972](https://app.circleci.com/pipelines/github/linkedin/cruise-control/1684/workflows/8e138488-addf-4e91-b996-d8345a3eb4ed/jobs/4972), [CI#4977](https://app.circleci.com/pipelines/github/linkedin/cruise-control/1686/workflows/cf13b527-0502-409e-ad38-93aaa236e72d/jobs/4977)). For example, the stack trace for the following test indicate that the admin client may fail to retrieve the expected throttle value from the broker. 
```
com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelperTest …
```
=> Revert "Update ReplicationThrottleHelper to use AdminClient (#1752)"

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsUtils.java
This PR attempts to resolve: https://github.com/linkedin/cruise-control/issues/1760
Add the ability for the metrics reporter to retry creating the producer while starting up. The number of retries is a configurable value, called "cruise.control.metrics.reporter.create.retries". The default number of retries is 2.
=> feat: Retry metrics reporter producer creation

.circleci/config.yml, build.gradle, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/BrokerFailureIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/DiskFailureIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlIntegrationTestUtils.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapacityViolationIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/DiskFailureDetector.java
In this pull request I introduced the disk failure test also with some configuration changes to speed up the tests a little bit. 
The DiskFailureIntegrationTest removes a  Kafka broker log folder and waits until the self healing fix the cluster.
I made a small change in the detector because under certain circumstances (from 10 test run 1 fails) the detector skips the detection. For example if the disk failure is detected but the self healing failed for this anomaly then the fix will not start again until there is no model change. That's why I modified the detector.
=> Add disk failure test and fix detection

.circleci/config.yml, build.gradle
Attempt to see if such pin can avoid being blocked by LI internal system check
=> Temporarily pull in jackson-databind 2.12.6.1 to resolve CVE alert

build.gradle
swagger-parser transitively pulls in jackson-databind, and the
vulnerable version is bumped in release 2.0.32.
See https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.32
This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR>.
=> Bump swagger-parser for CVE-2020-36518

build.gradle
This allows ./gradlew buildFatJar to work again since the migration to
Gradle 7.2
This PR resolves #1699.
Signed-of-by: Mike Lothian <mike@fireburn.co.uk>
=> Fix up buildFatJar gradle task

build.gradle
=> Revert "Bump swagger-parser for CVE-2020-36518 (#1815)"

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionUtilsTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelperTest.java
This PR resolves #1824 
Today, CruiseControl re-executes the inter-broker partition movement tasks in a batch if any task has partitions that's not being moved. The logic can cause unnecessary re-execution of partition movement.
For example:
There is a list of under-execution tasks: [task1, task2, task3, ...]. Task1 is to move partition1, and task2 is to move partition2, etc.
If partition1 is not being moved, while all of the partition2, 3, ..., are already being moved in the kafka cluster, cruise-control will re-execute all tasks. 
This is not necessary, as ideally cruise-control should only re-execute task1. This PR is to address this issue and only re-execute the task that doesn't have in-movement partition.
=> Remove execution tasks that have in-movement partitions from re-execution candidates

gradle.properties
Upgrade Netty and Jetty for CVE fixes.
Netty: [CVE-2022-24823](https://nvd.nist.gov/vuln/detail/CVE-2022-24823) - Fixed by upgrading to 4.1.78
Jetty: [CVE-2022-2047](https://nvd.nist.gov/vuln/detail/CVE-2022-2047) - fixed by upgrading to 9.4.48.v20220622
=> Upgrade Netty and Jetty dependencies for CVE fixes

gradle.properties
The previous PR https://github.com/linkedin/cruise-control/pull/1855 may introduce some potential risks. (The versions didn't pass our ELR check)
This PR is going to downgrade the versions back to a safer version.
=> Downgrade netty and jetty dependencies to a safer version

build.gradle, gradle/findbugs-exclude.xml
This PR resolves #1868.
-- I verified the fix. Before the fix I was getting the following warning in the SpotBugs report:
```
RCN | Nullcheck of response at line 78 of value previously dereferenced in com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusAdapter.queryMetric(String, long, long)
```
=> Bump up SpotBugs to resolve false positives with RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AbstractBrokerFailureDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ZKBrokerFailureDetector.java
This PR resolves #1876 .
**Description:**
In a previous PR, someone bumped the scala version from 2.12 to 2.13, and updated a bunch of APIs. For open source code, it doesn't have any issues. However, LinkedIn today still only supports scala 2.12. The API CollectionConverter that is supported by scala 2.13, is throwing exception in LinkedIn internal runtime.
This PR revert the API back to JavaConverter as a workaround. JavaConverter is an API in scala 2.12 and deprecated in scala 2.13 (still working though). With this change, it should fix the issue that LinkedIn is facing internally. For open source users, this PR shouldn't lead to any functional changes.
=> Fix the BrokerFailureDetector bug

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/UpdateTopicConfigurationRunnable.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/model/CreateOrDeleteReplicasTest.java
This PR resolves #1878 .
**Description:**
CruiseControl holds 2 versions of kafka cluster metadata:
1. ClusterModel: comes from the load monitor and may have fresher information
2. Cluster: comes from the metadata response from a kafka bootstrap server. 
The Cluster object may contain stale data if the kafka server has the stale metadata (which is possible because it takes time for kafka controller to send out the latest metadata to all brokers).
In that case, the data in Cluster may differ from the data in ClusterModel. E.g. a broker A can exist in Cluster but not in ClusterModel.
This PR is to take care of the above inconsistency during topic configuration change.
=> Handle the inconsistency between clusterModel and kafka metadata during update topic configuration

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/SlowBrokerFinder.java
This PR resolves #1896 
Example logs :
```
[2022-08-29 17:42:39,211] INFO Suspected Slow Brokers: [brokerId=14,host=b-14.XXXXXXXXX.c3.kafka.us-east-1.amazonaws.com] (com.linkedin.kafka.cruisecontrol.detector.SlowBrokerFinder)
32-07:00
[2022-08-29 17:42:39,231] INFO Slow Brokers Detected, description: {14 is slow (score: 50/50) since 2022-08-25T23:57:39Z} (com.linkedin.kafka.cruisecontrol.detector.SlowBrokerFinder)
```
=> Add more logging to SlowBrokerFinder

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetAssignmentPolicy.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetFileResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetResolutionHelper.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetResolver.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/ModuloBasedBrokerSetAssignmentPolicy.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/NoOpBrokerSetAssignmentPolicy.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/ReplicaToOriginalBrokerSetMappingPolicy.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/TopicNameHashBrokerSetMappingPolicy.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/KafkaClusterStateRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterBrokerState.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/KafkaClusterState.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetFileResolverTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/BrokerSetResolutionHelperTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/ModuloBasedBrokerSetAssignmentPolicyTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/NoOpBrokerSetAssignmentPolicyTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/config/TopicNameHashBrokerSetMappingPolicyTest.java
This PR resolves #1860.
**Description**:
This PR pass the BrokerSetResolver instance to KafkaClusterStateRequest, so that calling kafka_cluster_state endpoint would display the brokerSet information for each broker. E.g.
Along with that change, this PR deprecates several BrokerSetAwareGoal related APIs and creates replacements. Reasons:
- BrokerSetResolver is now used in both BrokerSetAwareGoal and KafkaClusterStateRequest. The available/accessible info is different in those 2 classes.
- BrokerSetAwareGoal has access to ClusterModel object.
- KafkaClusterStateRequest has access to Cluster object.
- In order to make BrokerSetResolver usable for both places, we have to expose an interface that has input param of commonly available info. In our case, it's the "rackIdByBrokerId" map. The map …
=> Display the brokerSet id in kafka_cluster_state endpoint.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionState.java
This PR resolves [#1905 ](https://github.com/linkedin/cruise-control/issues/1905)
Today, the way we determine a partition is an URP (Under Replicated Partition) based on the size of ISR and RS. E.g. if ISR = [A, B], and RS = [A, B, C], then the partition is treated as URP by CC.
However, in certain cases (usually because kafka is in a bad/inconsistent state), the ISR can be diverged from RS. E.g. ISR = [A, B, B], while RS = [D, E, F]. In this case, we still want CC to report this replica as URP, since the partition is not in a good state.
The proposal is, instead of comparing the size of ISR and RS, we should comparing the members in ISR and RS. If ISR != RS, CC should report it as URP.
=> Compare exact member of ISR with RS when deciding whether the partition is URP

build.gradle
2.1.3 is the latest version as of today on https://mvnrepository.com/artifact/io.swagger.parser.v3/swagger-parser-v3
This PR resolves #1924 .
=> Bumped swagger-parser-v3 version to 2.1.3

gradle.properties
=> Bump scala version to 2.13.10 (CVE-2022-36944)

cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/ReplicaCapacityViolationIntegrationTest.java, cruise-control/src/integrationTest/java/com/linkedin/kafka/cruisecontrol/TopicAnomalyIntegrationTest.java
Vertx integration test keeps failing and blocking release pipeline: https://app.circleci.com/pipelines/github/linkedin/cruise-control/2040/workflows/4578f8ca-c087-44e4-bd91-5d98f2480c32/jobs/5808. I'll have to disable it for now. @kismob fyi.
=> Disable vertx enabled integration test to unblock release pipeline

CONTRIBUTING.md
This PR resolves the comment in #1928.
Without a CircleCI account, the PR will fail to trigger the test pipelines. This is a required step for new contributors to create PRs for crusie-control.
=> Add create CircleCI account as a tip in CONTRIBUTING.md

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/concurrency/ExecutionConcurrencyManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/concurrency/ExecutionConcurrencySummary.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionConcurrencySummaryTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR resolves #1982.
This PR includes:
1. Avoid returning null for max/min/avg concurrencies if no ongoing execution. It will simply returns 0.
2. Add running state for ConcurrencyAdjuster and ConcurrencyManager. Only set state to running during execution.
3. Reseting the concurrency adjuster, manager and all concurrency values after execution. 
4. Add unit tests for the above 3 changes.
=> Add initialized state to concurrency adjuster and avoid null for the metric value

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/concurrency/ExecutionConcurrencyManager.java
This is to avoid errors when execution not starts.
=> Remove initialized check when get concurrency summary

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/BrokerSetAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CpuCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/CpuUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/DiskCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/DiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/MinTopicLeadersPerBrokerGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/NetworkInboundCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/NetworkInboundUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/NetworkOutboundCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/NetworkOutboundUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/PotentialNwOutGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/RackAwareGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/TopicReplicaDistributionGoal.java
Moved all implementations that are equivalent to `XXX.class.getSimpleName()` into `AbstractGoal#name()` with a dynamic `this.getClass().getSimpleName()`. This should avoid confusion for sub-classing.
=> [Refactor] Consolidate default Goal#name implementation

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/kafkaassigner/KafkaAssignerDiskUsageDistributionGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaTopicConfigProvider.java
This PR resolves #2004 .
KafkaCruiseControlConfig is initialized with doLogs set to true by default, which could generate lots of verbose logs. Recently we have seen another one of those incidents that someone init the KafkaCruiseControlConfig class without setting doLog to false. Since it is not the first time, and we don't see much values from the verbose config value logs, we updated the default doLog to false in this PR.
=> Change default doLog to false to avoid verbose logs during init CC config.

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionState.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/response/ClusterPartitionStateTest.java
**🌊 This PR resolves https://github.com/linkedin/cruise-control/issues/1828.** 
Currently, cruise-control detects offline partitions if the number of in-sync replicas is zero, and only performs this check if the partition is under-replicated. This definition of offline partitions is not comprehensive nor completely correct.
This PR corrects the detection of offline partitions by using the **status of a partition's leader** to determine whether a partition is offline. It also cleans up the conditional logic that determines whether a partition's status is checked to begin with.
1. Removed brokers in a test cluster to create offline partitions. Confirmed that offline partitions are listed on the cruise-control UI (screenshot above). Confirmed that values close to my change (eg. URPs, offline …
=> Set offline partitions as true if leader is null

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/notifier/SlackSelfHealingNotifier.java, docs/wiki/User Guide/Configure-notifications.md
We use a single slack channel to receive notifications from multiple Cruise Control instances. The current slack notifier does not provided any uniquely identifiable information in its text so it is not possible to know from what instance a particular alert came from.
The notifier does let you customise the username and icon, which could allow us distinguish the alerts. However, as per that Slack webhook [docs](https://api.slack.com/messaging/webhooks#advanced_message_formatting):
> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.
This PR provides a simple solution by allowing a preamble string to …
=> Add option to add preamble text to all slack notifications

build.gradle, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java
This PR resolves #2018.
This PR future proofs Cruise Control against breaking changes coming with Kafka 3.5. Tested against a Kafka 3.5 cluster and a Kafka 3.4 cluster 
Let me know if it is preferable to submit this against a new  `migrate_to_kafka_3_5` branch. 
Let me know what you think!
=> Future-proof against Kafka 3.5 breaking changes

build.gradle, gradle.properties
=> Upgrade vertx to 4.4.3 due to CVE-2023-24815

build.gradle
This PR resolves #1996.
Tested on Java 11. The only difference in generated JAR file is single MANIFEST.MF entry. With this change warning from linked issue disappears.
=> Generate Multi-Release fat JAR

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java
This PR is to enable info level log after each goal optimization.
Previously the log is a debug level log. Since we believe this log expose critical information of Cruise Control at runtime, we enabled the log in this PR. In addition, we add provision status to the log to show what of the provision status of each goal.
=> Enable info level log after each goal optimization

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/ZKBrokerFailureDetector.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/task/LoadMonitorTaskRunner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/AddBrokerRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/ClusterLoadRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/CruiseControlStateRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/DemoteRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/FixOfflineReplicasRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/PartitionLoadRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/ProposalsRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/RebalanceRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/RemoveBrokerRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/TopicConfigurationRequest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetectorManagerTest.java
This PR resolves #2052 
- We should use `ExecutorService#execute` to make uncaught exception handler works
* In most places, we don't need return value of `submit`
=> Use ExecutorService.execute where return value is unnecessary to make uncaught exception handler works fixes #2052

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/CruiseControlParametersConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/CruiseControlRequestConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/Disk.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/CruiseControlEndPoint.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/RemoveDisksRequest.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveDisksRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/RemoveDisksParameters.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/OptimizationResult.java, cruise-control/src/main/resources/yaml/base.yaml, cruise-control/src/main/resources/yaml/endpoints/removeDisks.yaml, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/RemoveDisksTest.java
This PR resolves #1907 .
This PR introduces a new endpoint that moves replicas from a specified disk to other disks of the same broker. This will allow the removal of the disk without the loss of data.
The replicas are moved in a round-robin manner to the remaining disks, from the largest to the smallest, while checking the following constraint:
```
1 - (remainingUsageAfterRemoval / remainingCapacity) > errorMargin
```
where
```
remainingUsageAfterRemoval = current usage for remaining disks + additional usage from removed disks
remainingCapacity = sum of capacities of the remaining disks
errorMargin = configurable property (default 0.1); it makes sure that a disk percentage is always free when moving replicas
```
The new endpoint is available as follows:
```
POST …
```
=> Add endpoint to move all replicas from a disk to other disks of the same broker

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR resolves #2068.
This fix has markTaskExecutionFinished to update the endpoint timer metrics when the execution is done and also eliminates the race condition between checkActiveUserTasks and startExecution on updating the metrics.
=> Fix endpoint metrics involving task execution

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/executor/ExecutorTest.java
This PR fixes the deadlock introduced by PR #2069 by partially reverting changes in that PR by moving _userTaskManager.markTaskExecutionBegan(_uuid) from the constructor of ProposalExecutionRunnable back to its run() thread. This avoids the deadlock formed between Executor and UserTaskManager. The initialization of ProposalExecutionRunnable is under Executor's monitor lock and _userTaskManager.markTaskExecutionBegan aquires UserTaskManager's monitor lock. On the other hand, the process of StopProposalRequest enters UserTaskManager's monitor lock first, and then acquires Executor's monitor lock. 
With this change, we would have the issue back that [request]-successful-request-execution-timer may or may not record the proposal computing time for request that requires proposal execution …
=> Fix deadlock between Executor and UserTaskManager

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java
- Increase log severity for proposals generation failure: `INFO` -> `WARN`
- in order to increase visibility
1. `$ ./gradlew test`
=> Increase log severity for proposals generation failure from `INFO` to `WARN`

README.md
- Kafka 3 is supported since #1788 making `migrate_to_kafka_2_5` default branch misleading
- logs `migrate_to_kafka_2_5` -> `main` branch migration
- update README
This PR resolves [We should update the README for kafka-version support · Issue #2134 · linkedin/cruise-control][1]
[1]:https://github.com/linkedin/cruise-control/issues/2134#event-12188013773
Steps to update your branch to get merged to `main`
```
git branch -m migrate_to_kafka_2_5 main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> `main` branch migration

gradle.properties
A number of java interop issues have been resolved in scala:
https://github.com/scala/scala/pulls?q=label%3A%22java+interop%22+is%3Aclosed
As it stands compiling using jdk 21 fails with:
```
116.0 > Task :cruise-control:compileScala
116.0 error:
116.0   bad constant pool index: 0 at pos: 48461
116.0      while compiling: <no file>
116.0         during phase: globalPhase=<no phase>, enteringPhase=<some phase>
116.0      library version: version 2.13.10
116.0     compiler version: version 2.13.10
```
Its not clear which of the versions between .10 and .13 resolves it but I think its safe to move to [.13](https://github.com/scala/scala/releases) which also happens to resolve the compile issue.
This PR resolves #2138.
=> update scala to support java 21

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/AbstractGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/GoalUtilsTest.java
=> Consider max RF when assessing whether the cluster is over-provisioned

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
Fix issue: https://github.com/linkedin/cruise-control/issues/2168
When running embedded MetricsReporter with the upcoming Kafka 3.8, hit the following exception:
[2024-06-18 16:08:06,722] ERROR [KafkaServer id=1025] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) java.lang.NoSuchMethodError: 'java.lang.String kafka.server.KafkaConfig.ListenersProp()' at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.getBootstrapServers(CruiseControlMetricsReporter.java:129)
The root cause is Kafka 3.8 (maybe also 3.7) refactored the core module for many configuration parameters, see this PR: apache/kafka@1b301b3?diff=split&w=0#diff-8eb3e01716508551f203b0b37c2d5f951e93cce7ffed7c00c2b33633d7c8ed23
The easiest fix is just to use hard-coded …
=> Use literal config name for listeners and broker.id config

build.gradle
Exclude logback from being depended on transitively (following established pattern for excluding log4j:log4j)
Why:
A logback slf4j binding is being pulled in via zookeeper causing issues at runtime because we have two slf4j bindings available. Slf4j chooses one implementation and it can pick logback, which is unexpected.
To reproduce on `main`:
```
gradle clean build -q -x test && ./kafka-cruise-control-start.sh config/cruisecontrol.properties 2>&1 | grep SLF4J
... gradle noises ...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/robeyoun/development/upstream/cruise-control/cruise-control/build/dependant-libs/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in …
```
=> bugfix: exclude transitive logback dependencies

build.gradle
Upgrading simplekdc version to "2.1.0" which supports a change that can correctly use security classes based on what version of IBM Semeru JDK(if applicable) is being used.
There is no regression observed using Semeru, OpenJDK and Temurin JDKs.
This newer version(released on 14 August 2024) also caters vulnerability in deps mentioned  [here](https://github.com/linkedin/cruise-control/pull/2179#issuecomment-2297676772) as **org.jboss.xnio:xnio-api** is updated to [**3.8.16**](https://github.com/apache/directory-kerby/releases/tag/kerby-all-2.1.0#:~:text=Bump%20org.jboss.xnio%3Axnio%2Dapi%20from%203.8.15.Final%20to%203.8.16.Final).
cc @mhratson 
This PR resolves #2178
=> Upgrade simplekdc to 2.1.0

cruise-control-core/src/main/java/com/linkedin/cruisecontrol/common/Generationed.java, cruise-control-core/src/main/java/com/linkedin/cruisecontrol/monitor/sampling/aggregator/MetricSampleAggregatorState.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/ContainerMetricUtils.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ReplicaCapacityGoal.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ExecutionTaskPlanner.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java
Fix the typo 'the the' in the comment.
=> fix typo in comment

.github/workflows/artifactory.yaml, .github/workflows/ci.yaml
1. GIthub Actions workflow are native GH workflows 
2. Github Actions do not require additional non-github accounts unlike CircleCI
3. plenty of compute resources[^0] available for OSS projects
4. unlike CircleCI resource limits (don't have details)
[^0]:https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#availability
1. creates CI workflow `ci.yaml`
2. creates Artifactory workflow: `artifactory.yaml`
Workflow structure is documented in the spec[^1]
[^1]:https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
CI is expected to 
1. execute unit tests
1. execute integration tests
1. execute hw platform unit tests 
1. publish artifacts to the artifactory when a tag is published
1. provide ability to re-run …
=> CI workflow with Github Actions

cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/utils/CCEmbeddedZookeeper.java
1. Why: when on VPN, I can't run Cruise Control tests as ZK is binding to local real ip address and local network is restricted.
2. What: changing to bind to 127.0.0.1 fixes it (got the idea from Kafka embedded ZK setup. I think it won't make any difference how automation or human would run the tests, pls correct me if I'm wrong.
=> Set Embedded Zookeeper listen on 127.0.0.1

docs/pull_request_template.md
1. Why:  to categorize documentation PRs
2. What: adds "documentation" category to the PR template
- when users make documentation changes
- they should be able to specify documentation as a change category
- no documentation category to specify
n/a
n/a
=> Add documentation category to PR template

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/progress/OperationProgress.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/GoalBasedOperationRunnable.java
1. Why: 
Some cruise control operation, like broker removal, has to go through a few steps. It may also be in pending state for some time due to thread pool resource limitations or ongoing operations. We want to have additional observability on the time it takes for each step so that we know where the potential improvement will be.
2. What: 
Additional loggings are added to track the total time and time spent on each step for the goal based operation.
=> Add more logging to help debugging the time spent on goal based operation

.circleci/config.yml
1. Why: 
`test-multi-arch` job fails due to image ubuntu-2004:202107-02 is unavailable. See https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/.
On the other hand, builds and integration tests on other platforms pass.
2. What: 
Removed the job `test-multi-arch` to unblock the PR workflow.
I also tried to fix this by using the `default` machine image as suggested in the above link but it [failed](https://app.circleci.com/pipelines/github/linkedin/cruise-control/2467/workflows/42acc46b-01da-44cc-8fff-d06800a6f1d7/jobs/6740) in findbugs due to class file version issue. 
- [x ] other
=> Fix the Circle CI error by removing the test-multi-arch job

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/GoalBasedOperationRunnable.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/runnable/RemoveBrokersRunnable.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/detector/MaintenanceEventTest.java
1. Why: 
We want to track and analyze task execution for each task in the log analysis tool. But currently there is not enough information logged and the log does not have task UUID so it is difficult to track on the per task base.
2. What: 
Added more INFO logging with UUID.
Also fixed a bug where `null` UUID is logged by moving the call to `clearCompletedExecution()` (where uuid is reset to `null`) to after the logging.
```
Execution succeeded: task Id: null; removed brokers: [103986]; demoted brokers: null; total time used: 874448ms.. 
```
- [x ] bugfix
- [ x] other
=> Improve per task observability through additional logging

cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
1. Why: The test failed sometimes with unexpected method calls.
2. What: The fix is preparing the test to accept invalidate method call too
Tests are running without failure
Tests are failing sometimes with unexpected method call.
1. setup repeated run on e.g. `testCreateUserTask` in IDE
2. observe failure after multiple successful runs (for me it was failing after around 250 successful runs)
```
java.lang.AssertionError: On mock #2 (zero indexed): 
Unexpected method calls:
HttpSession.invalidate()
at org.easymock.EasyMock.getAssertionError(EasyMock.java:2230)
at org.easymock.EasyMock.verify(EasyMock.java:2058)
at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManagerTest.testCreateUserTask(UserTaskManagerTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Na …
```
=> Fixing Unexpected method calls: HttpSession.invalidate

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
1. Why: KafkaCruiseControlConfig sanity checks prevent to configure inter broker goals as default goals.
2. What: Modify the sanity check to allow adding intra broker goals to the `default.goals`
I can add (enable) goals to the `default.goals` list from both the intra and inter broker goals
Sanity checks ensure the following rules:
- **goals and intra broker goals should be disjoint** (an intra broker goal cant be in the `goals` and the `intra.broker.goals` at the same time)
- **`default.goals` should be a subset of `goals`** (As a result of this, we could not add intra broker goal to the `default.goals`)
- **`intra.broker.goals` cant be empty** (you could not move all the intra broker roles to the goals)
We could not add intra goal to the `default.goals` without a trick (see in the …
=> Fix: intra.broker.goals cannot be configured as default.goals

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/WebServerConfig.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/DummyAuthorizationService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/PrincipalName.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/PrincipalValidator.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoLoginServiceWithAuthServiceLifecycle.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoSecurityProvider.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginService.java, cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProvider.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoLoginServiceWithAuthServiceLifecycleTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoSecurityProviderIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoSecurityProviderTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/spnego/SpnegoSecurityProviderWithAtlRulesIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxyLoginServiceTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderSpnegoFallbackIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderSpnegoFallbackWithAtlRulesIntegrationTest.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderTestUtils.java, cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/security/trustedproxy/TrustedProxySecurityProviderWithAtlRulesIntegrationTest.java, cruise-control/src/test/resources/auth-atlrules.credentials, docs/wiki/User Guide/Security.md
=> Kerberos auth to local rules support

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaAdminTopicConfigProvider.java
If the `AdminClient` fails to describe the cluster, the exception is not exposed.
```
2024-09-23 20:03:28,871 ERROR com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain: [main]: Uncaught exception on thread Thread[main,5,main]
java.lang.RuntimeException: Failed to describe Kafka cluster configs.
at com.linkedin.kafka.cruisecontrol.config.KafkaAdminTopicConfigProvider.configure(KafkaAdminTopicConfigProvider.java:174) ~[cruise-control-2.5.116.jar:?]
at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfigUtils.getConfiguredInstance(KafkaCruiseControlConfigUtils.java:49) ~[cruise-control-2.5.116.jar:?]
at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:98) ~[cruise-control-2.5.116.jar:?]
at …
```
=> Expose AdminClient exception when failing to describe the cluster

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/PartitionSizeAnomalyFinder.java
1. Why: I ran into the following exception when I tried to customize the SELF_HEALING_PARTITION_SIZE_THRESHOLD_MB in PartitionSizeAnomalyFinder
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
at com.linkedin.kafka.cruisecontrol.detector.PartitionSizeAnomalyFinder.configure(PartitionSizeAnomalyFinder.java:111) ~[classes/:?]
at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstances(KafkaCruiseControlConfig.java:119) ~[classes/:?]
at com.linkedin.kafka.cruisecontrol.detector.TopicAnomalyDetector.<init>(TopicAnomalyDetector.java:32) ~[classes/:?]
at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager.<init>(Anoma …
```
=> Fix PartitionSizeAnomalyFinder, to be able to handle custom SELF_HEALING_PARTITION_SIZE_THRESHOLD_MB value

.github/workflows/ci.yaml
1. Why: Currently GHA CI builds for s390x are failing consistently, blocking the CI workflow.
2. What: Added correct way of running multiple instructions during docker run command, updated temurin image to 11-jdk so that it can be in sync with ubuntu-latest image and introduced continue-on-error due to intermittent test case failures on temurin container.
`gradle build` command should run inside the s390x emulated temurin container and should pass.
gradle command actually runs on ubuntu-latest(which is x86_64) image which may or may not fail based on ubuntu-latest's jdk version which keeps on updating.
1. Check GHA CI build log for s390x 
No
1. This issue is similar to https://github.com/linkedin/cruise-control/issues/2209 which is happening on CircleCI instead of GHA, where we discussed …
=> Rectify GHA CI workflow for s390x

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AbstractBrokerFailureDetector.java
By enabling broker failure detection with `kafka.broker.failure.detection.enable=true` we have got a CC log (on the first startup without any brokers' failures) which print an error like this:
```shell
2025-03-03 11:53:29 ERROR AbstractBrokerFailureDetector:126 - Failed to load the failed broker list.
java.nio.file.NoSuchFileException: fileStore/failedBrokers.txt
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
at …
```
=> Catch NoSuchFileException on load failed brokers list

cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java, cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/exception/KafkaTopicDescriptionException.java, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterAutoCreateTopicTest.java, cruise-control-metrics-reporter/src/test/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterTest.java
1. Why: Cruise Control metrics reporter package seems to be using some deprecated method for some time now which are completely removed in Kafka 4.0.0. These deprecated method makes CC incompatible with Kafka 4.0 and beyond.
```
2025-02-22T22:27:38,802 ERROR Uncaught exception in thread 'CruiseControlMetricsReporterRunner': (org.apache.kafka.common.utils.KafkaThread) [CruiseControlMetricsReporterRunner]
java.lang.NoSuchMethodError: 'java.util.Map org.apache.kafka.clients.admin.DescribeTopicsResult.values()'
at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.maybeIncreaseTopicPartitionCount(CruiseControlMetricsReporter.java:376) ~[cruise-control-metrics-reporter-2.5.141.jar:?]
at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.mayb …
```
=> Replace deprecated methods to support Kafka 4.0.0

cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java
1. Why
We run kafka 3.0 with the 3.0.0 version and get the following error:
```
java.util.NoSuchElementException: Unable to find viable apply function version for the KafkaZkClient class 
at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlUtils.createKafkaZkClient(KafkaCruiseControlUtils.java:572) ~[com.linkedin.cruisec
ontrol.cruise-control-3.0.0.jar:?]
at com.linkedin.kafka.cruisecontrol.detector.ZKBrokerFailureDetector.<init>(ZKBrokerFailureDetector.java:46) ~[com.linkedin.cruisecontro
l.cruise-control-3.0.0.jar:?]
at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager.<init>(AnomalyDetectorManager.java:116) ~[com.linkedin.cruisecontrol
.cruise-control-3.0.0.jar:?]
at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:124) …
```
=> Change log level in createKafkaZkClient

.circleci/config.yml, .github/workflows/artifactory.yaml, .github/workflows/ci.yaml, README.md, build.gradle
1. Why: Jetty 12 requires a minimum of Java 17, so Java 11 must be dropped to facilitate this upgrade #2307. The current version of Jetty in cruise-control is 9.4.56.v20240826. This version contains two CVEs 
- CVE-2024-13009 - patched in 9.4.57.v20241219
- CVE-2024-6763 - patched in 12.0.12
So, Jetty 12 is needed to patch CVE-2024-6763.
2. What: Remove support support for Java 11. Raise minimum JDK to 17 in builds, docs, and workflows
=> Remove support for Java 11
